### ISSUE TITLE
Metrics of pcp-pmda-mounts are missing help texts.

### ISSUE THREAD

**Issue by kurik** [performancecopilot/pcp#1267] opened 2021-05-10 16:26 UTC
Metrics of pcp-pmda-mounts are missing help texts.

The following metrics of pcp-pmda-mounts are missing online help texts.
This is output of ```pminfo -t``` filtered to metrics without a help text:
```
mounts.device One-line Help: Error: One-line or help text is not available
mounts.type One-line Help: Error: One-line or help text is not available
mounts.options One-line Help: Error: One-line or help text is not available
mounts.up One-line Help: Error: One-line or help text is not available
mounts.capacity One-line Help: Error: One-line or help text is not available
mounts.used One-line Help: Error: One-line or help text is not available
mounts.free One-line Help: Error: One-line or help text is not available
mounts.maxfiles One-line Help: Error: One-line or help text is not available
mounts.usedfiles One-line Help: Error: One-line or help text is not available
mounts.freefiles One-line Help: Error: One-line or help text is not available
mounts.full One-line Help: Error: One-line or help text is not available
mounts.blocksize One-line Help: Error: One-line or help text is not available
mounts.avail One-line Help: Error: One-line or help text is not available
mounts.availfiles One-line Help: Error: One-line or help text is not available
mounts.readonly One-line Help: Error: One-line or help text is not available
```

The following metrics of pcp-pmda-mounts are missing full help texts.
This is output of ```pminfo -T``` filtered to metrics without a help text:
```

mounts.device
Full Help: Error: One-line or help text is not available

mounts.type
Full Help: Error: One-line or help text is not available

mounts.options
Full Help: Error: One-line or help text is not available

mounts.up
Full Help: Error: One-line or help text is not available

mounts.capacity
Full Help: Error: One-line or help text is not available

mounts.used
Full Help: Error: One-line or help text is not available

mounts.free
Full Help: Error: One-line or help text is not available

mounts.maxfiles
Full Help: Error: One-line or help text is not available

mounts.usedfiles
Full Help: Error: One-line or help text is not available

mounts.freefiles
Full Help: Error: One-line or help text is not available

mounts.full
Full Help: Error: One-line or help text is not available

mounts.blocksize
Full Help: Error: One-line or help text is not available

mounts.avail
Full Help: Error: One-line or help text is not available

mounts.availfiles
Full Help: Error: One-line or help text is not available

mounts.readonly
Full Help: Error: One-line or help text is not available
```

**Comment by kmcdonell** [comment] 2023-05-10 21:43
This issue is not understood, but it is not apparently reproducible.  The help text files for this PMDA are packaged and installed and appear to be available once the PMDA is in use by pmcd(1).
Closing the issue, please re-open if the problem is observed again.

**Closed by kmcdonell** 2023-05-10 21:43 UTC
