### ISSUE TITLE
Metrics of pcp-pmda-lustrecomm are missing help texts.

### ISSUE THREAD

**Issue by kurik** [performancecopilot/pcp#1265] opened 2021-05-10 16:24 UTC
Metrics of pcp-pmda-lustrecomm are missing help texts.

The following metrics of pcp-pmda-lustrecomm are missing online help texts.
This is output of ```pminfo -t``` filtered to metrics without a help text:
```
lustrecomm.timeout One-line Help: Error: One-line or help text is not available
lustrecomm.ldlm_timeout One-line Help: Error: One-line or help text is not available
lustrecomm.dump_on_timeout One-line Help: Error: One-line or help text is not available
lustrecomm.lustre_memused One-line Help: Error: One-line or help text is not available
lustrecomm.lnet_memused One-line Help: Error: One-line or help text is not available
lustrecomm.stats.msgs_alloc One-line Help: Error: One-line or help text is not available
lustrecomm.stats.msgs_max One-line Help: Error: One-line or help text is not available
lustrecomm.stats.errors One-line Help: Error: One-line or help text is not available
lustrecomm.stats.send_count One-line Help: Error: One-line or help text is not available
lustrecomm.stats.recv_count One-line Help: Error: One-line or help text is not available
lustrecomm.stats.route_count One-line Help: Error: One-line or help text is not available
lustrecomm.stats.drop_count One-line Help: Error: One-line or help text is not available
lustrecomm.stats.send_length One-line Help: Error: One-line or help text is not available
lustrecomm.stats.recv_length One-line Help: Error: One-line or help text is not available
lustrecomm.stats.route_length One-line Help: Error: One-line or help text is not available
lustrecomm.stats.drop_length One-line Help: Error: One-line or help text is not available
```

The following metrics of pcp-pmda-lustrecomm are missing full help texts.
This is output of ```pminfo -T``` filtered to metrics without a help text:
```

lustrecomm.timeout
Full Help: Error: One-line or help text is not available

lustrecomm.ldlm_timeout
Full Help: Error: One-line or help text is not available

lustrecomm.dump_on_timeout
Full Help: Error: One-line or help text is not available

lustrecomm.lustre_memused
Full Help: Error: One-line or help text is not available

lustrecomm.lnet_memused
Full Help: Error: One-line or help text is not available

lustrecomm.stats.msgs_alloc
Full Help: Error: One-line or help text is not available

lustrecomm.stats.msgs_max
Full Help: Error: One-line or help text is not available

lustrecomm.stats.errors
Full Help: Error: One-line or help text is not available

lustrecomm.stats.send_count
Full Help: Error: One-line or help text is not available

lustrecomm.stats.recv_count
Full Help: Error: One-line or help text is not available

lustrecomm.stats.route_count
Full Help: Error: One-line or help text is not available

lustrecomm.stats.drop_count
Full Help: Error: One-line or help text is not available

lustrecomm.stats.send_length
Full Help: Error: One-line or help text is not available

lustrecomm.stats.recv_length
Full Help: Error: One-line or help text is not available

lustrecomm.stats.route_length
Full Help: Error: One-line or help text is not available

lustrecomm.stats.drop_length
Full Help: Error: One-line or help text is not available
```

**Comment by kmcdonell** [comment] 2023-05-10 21:44
This issue is not understood, but it is not apparently reproducible.  The help text files for this PMDA are packaged and installed and appear to be available once the PMDA is in use by pmcd(1).
Closing the issue, please re-open if the problem is observed again.

**Comment by kmcdonell** [comment] 2023-05-10 21:49
This issue is not understood, but it is not apparently reproducible.  The help text files for this PMDA are packaged and installed and appear to be available once the PMDA is in use by pmcd(1).
Closing the issue, please re-open if the problem is observed again.

**Closed by kmcdonell** 2023-05-10 21:49 UTC
