### ISSUE TITLE
pcp-gui : Depends: libgcc-s1 (>= 3.0) but it is not installable on Ubuntu 18.04.5LTS Bionic

### ISSUE THREAD

**Issue by torehl** [performancecopilot/pcp#1368] opened 2021-08-27 13:38 UTC
Hi,

       pcp-gui 5.3.2-1 seems to be dependent on a non-existent package on Bionic.  Suggestions?  libgcc-s1 is probably libgcc1 on Bionic.

root@srl-adm1:~# apt install -y pcp pcp-doc pcp-gui libgcc1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libgcc1 is already the newest version (1:8.4.0-1ubuntu1~18.04).
pcp is already the newest version (5.3.2-1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pcp-gui : Depends: libgcc-s1 (>= 3.0) but it is not installable
E: Unable to correct problems, you have held broken packages.

      OS:

root@srl-adm1:~# lsb_release -a
LSB Version:	core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

**Comment by kmcdonell** [comment] 2021-08-29 22:17
@torehl I'm a bit puzzled by this.  I have 2 Ubuntu 18.04.5 LTS (Bionic Beaver) VMs (one i686, one x86_64) in my QA Farm, and I've never seen the issue you're reporting with regular builds from source and package installs.
```
kenj@vm20:~$ dpkg -l pcp-gui
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  pcp-gui        5.3.3-1      amd64        Visualisation tools for the Perfo
```
And my libgcc dependency is
```
kenj@vm20:~$ apt-cache depends pcp-gui | grep gcc
  Depends: libgcc1
```
So I guess the first question is where did you get your PCP 5.3.2-1 packages from?

**Comment by torehl** [comment] 2021-08-30 09:22
Hi Ken,

      How are things down under? 
     
      It is from performancecopilot.jfrog.io. Maybe I have it wrong? 

root@ipu-pod64-server1:~# cat /etc/apt/sources.list.d/pcp.list
# deb https://dl.bintray.com/pcp/bionic bionic main
# deb https://performancecopilot.jfrog.io/artifactory/pcp-deb-release/ubuntu/18.04/amd64/pcp
# curl https://performancecopilot.jfrog.io/artifactory/api/security/keypair/default-gpg-key/public | apt-key add -
deb https://performancecopilot.jfrog.io/artifactory/pcp-deb-release bionic main

root@ipu-pod64-server1:~# apt-cache depends pcp-gui | grep gcc
  Depends: <libgcc-s1>

**Comment by kmcdonell** [comment] 2021-08-30 21:33
G'day Tore,

Modulo COVID lockdowns, things are good down under.

Everything looks OK with your repo setup, and I can reproduce the problem using the pcp-gui_5.3.2-1_amd64.deb package from performancecopilot.jfrog.io.

So it is most likely an issue with the particular VM used to generate the packages, I'll go consult @andreasgerstmayr who's the build meister in this area.

If you have an urgent need, let me know and I'll spin you a new pcp-gui_5.3.2 and put it someplace where you can access it, otherwise I'll add to this issue when we understand the root cause, hopefully before the 5.3.3 packages are spun up.

**Comment by andreasgerstmayr** [comment] 2021-08-31 11:02
I can see where the issue is - for Ubuntu 18.04 and Ubuntu 20.04 we're using the GitHub provided images directly, without using a container to build PCP. This has the advantage that we have a real VM, and no container, but it unfortunately isn't a 100% stock Ubuntu image. It does the following extra things: https://github.com/actions/virtual-environments/blob/main/images/linux/ubuntu1804.json and https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/gcc.sh for example - i.e. installing more recent compiler toolkits and package versions.

I checked where the libgcc-s1 is coming from:
```
$ apt-cache policy libgcc-s1
libgcc-s1:
  Installed: 11.1.0-1ubuntu1~18.04.1
  Candidate: 11.1.0-1ubuntu1~18.04.1
  Version table:
 *** 11.1.0-1ubuntu1~18.04.1 500
        500 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```

I'll take care that for the next PCP release everything is built in a container, where we have full control over what's installed, and there won't be any dependencies outside the stock Ubuntu package repository.

For QA purposes we'll still need direct VMs, as some things can't be tested in a container (the eBPF PMDAs for example ... or I'll try again to mount the kernel headers etc. from the host, but afaics there were still some issues).

**Comment by andreasgerstmayr** [comment] 2021-08-31 15:33
should be fixed with 134266a2a3bfb0c40ef1bf5c6104197f2944191e for the next release

**Comment by torehl** [comment] 2021-09-01 08:19
Thanks Ken and Andreas. I can wait until next release.

**Comment by andreasgerstmayr** [comment] 2021-09-07 14:42
Verified with `build-ubuntu1804-container` from https://github.com/performancecopilot/pcp/actions/runs/1206998383

```
$ dpkg -I pcp-gui_5.3.3-0.20210906.5758d58_amd64.deb | grep gcc
 Depends: libc6 (>= 2.14), libgcc1 (>= 1:3.0), libpcp3, libqt5core5a (>= 5.9.0~beta), libqt5gui5 (>= 5.8.0), libqt5network5 (>= 5.0.2), libqt5printsupport5 (>= 5.0.2), libqt5svg5 (>= 5.6.0~beta), libqt5widgets5 (>= 5.2.0~alpha1), libstdc++6 (>= 5.2)
```

Closing this issue.

**Closed by andreasgerstmayr** 2021-09-07 14:42 UTC

**Comment by andreasgerstmayr** [comment] 2021-09-15 12:17
@torehl: PCP version 5.3.3 got released today, you can try it out now if you want.
