### ISSUE TITLE
pmmgr-3.11.10 breaks backwards compatibility

### ISSUE THREAD

**Issue by screentan** [performancecopilot/pcp#307] opened 2017-06-07 23:49 UTC
We use pcp2graphite under pmmgr to pull pcp from many clients to a central server running graphite.  The clients are all running pcp-3.10.9 from Redhat/Centos.  This worked fine for months but broke when we upgraded the pmmgr central system (using the bintray repo) from 3.11.9 to 3.11.10.  Under 3.11.10 the pcp2graphite processes would run for just over an hour before pmmgr declared the client dead and killed pcp2graphite.  We have two clients running 3.11.10 (also using bintray repo) for the newer SCSI tape io support and the pcp2graphite processes continued for those.  We down graded the central server from 3.11.10 to 3.11.9 and things work fine again.

**Comment by fche** [comment] 2017-06-08 00:19
Chances are this is related to the libpcp pdu/ctxnumber changes that were made shortly before 3.11.10, fixes to which are just making their way into pcp master.  You can work around this particular problem by periodically restarting pmmgr.  I'm surprised it only takes an hour for the problem to trigger; are you monitoring a large number of clients?

**Comment by screentan** [comment] 2017-06-08 17:45
We are polling 30 clients at 10sec interval with about 1200 metrics per system.

**Comment by fche** [comment] 2017-07-01 22:59
Please test pcp 3.12.0; it appears to fix the libpcp/pmcd bugs that manifest themselves this way.

**Comment by kmcdonell** [comment] 2017-11-24 19:21
I think this was a transient effect of the changes Frank referred to, and on that basis I'm closing the issue.

If the issue is not fixed or re-appears, please reopen with new information.

**Closed by kmcdonell** 2017-11-24 19:21 UTC
