### ISSUE TITLE
secondary pmlogger(s) ignore /etc/sysconfig/pmlogger

### ISSUE THREAD

**Issue by andreasgerstmayr** [performancecopilot/pcp#1214] opened 2021-02-17 19:13 UTC
I installed pcp-zeroconf which sets `PMLOGGER_INTERVAL=10` in `/etc/sysconfig/pmlogger`.

It works fine for the primary pmlogger, but other remote loggers do not respect this setting and are logging with the default of 60s.

I triaged the bug: https://github.com/performancecopilot/pcp/blob/1f8f6fad803ef2c5f7d1e24135d2749ee99cedc2/src/pmlogger/pmlogger_check.sh#L928-L954

Only for the primary logger we're reading this file, otherwise `envs` is empty.

If this is expected, it needs to be documented in the comment above `PMLOGGER_INTERVAL` in `/etc/sysconfig/pmlogger`. If it's not expected (I as a user didn't expect it) we need to move the ```envs=`grep ...``` line out of the if condition.

**Comment by natoscott** [comment] 2021-02-18 06:01
I *think* this was an oversight rather than the original intent - I vote for making the setting applicable to all pmlogger processes.

**Comment by kmcdonell** [comment] 2021-02-18 20:44
I don't think it was an oversight ... another example of the uneasy truce between pcp and systemd ... these other loggers are not directly controlled by systemd and they (like the primary logger) have a well established way of setting env vars through their control files.  Now we don't have a way of doing it globally for all pmloggers, but that's not necessarily an argument for saying "put the global stuff in a systemd control file" ... so, what happens for non-systemd installations?  Do they just not get the feature?
I know I'm fighting a losing battle against systemd, but it is a over-featured square peg in pcp's round hole!

**Comment by andreasgerstmayr** [comment] 2021-02-18 20:59
I can't see how this issue is related to systemd? The problem is in `pmlogger_check.sh`, which is used in both systemd and non-systemd init systems. There is a condition which reads `$PCP_SYSCONFIG_DIR/pmlogger` only in the case of a primary pmlogger.

**Comment by kmcdonell** [comment] 2021-02-18 21:14
Mea culpa @andreasgerstmayr ... I did not look closely enough.  $PCP_SYSCONFIG_DIR has nothing to do with systemd.
So I revise my vote and I'm +1 with @natoscott.

**Comment by andreasgerstmayr** [comment] 2021-02-22 12:36
Just thinking about the impact for existing installations -
pcp-zeroconf users will suddenly log metrics every 10s instead of 60s, if they have remote loggers configured and didn't set the interval explicitly in the control file, and the Redis database will grow much faster (if redis/pmproxy are enabled).

Even though applying this setting to all loggers seems to be the right thing to do, we might get complaints soon ("disk space is suddenly growing much faster than with the previous PCP release, please fix this bug!", looking back at the recent issues with the `Requires=pmcd` change). Maybe we should document it instead in `/etc/sysconfig/pmlogger`? I see it as a bug (same as the Requires=pmcd), but by now people might depend on this behavior and interpret changes to this behavior as a regression.

What do you think?

**Comment by natoscott** [comment] 2021-02-22 21:32
We could perhaps add a new variable for the non-local case, like PMLOGGER_REMOTE_INTERVAL or something like that?

**Comment by goodwinos** [comment] 2021-03-02 23:22
This is a bug and we should just fix it. It's not only the PMLOGGER_INTERVAL default value that's missing from the environment of non-primary loggers.

re: adding a new PMLOGGER_REMOTE_INTERVAL .. not sure what we'd gain from that? IMO it's already complicated enough having three levels of intervals (PMLOGGER_INTERVAL in the environment, -t on the command line and explicit (non default) intervals specified in the pmlogger config file for specific blocks of metrics, each overriding in that order). 

Re: existing sites running logger farms - only sites with pcp-zeroconf or who have manually tweaked their sysconfig will see a change (for only their non-primary loggers, if any). We'll just have to document the potential disk space changes and redis memory usage in release notes / doctext.

**Comment by andreasgerstmayr** [comment] 2021-03-03 18:42
> This is a bug and we should just fix it. It's not only the PMLOGGER_INTERVAL default value that's missing from the environment of non-primary loggers.

+1

> re: adding a new PMLOGGER_REMOTE_INTERVAL .. not sure what we'd gain from that? IMO it's already complicated enough having three levels of intervals (PMLOGGER_INTERVAL in the environment, -t on the command line and explicit (non default) intervals specified in the pmlogger config file for specific blocks of metrics, each overriding in that order).

+1

> Re: existing sites running logger farms - only sites with pcp-zeroconf or who have manually tweaked their sysconfig will see a change (for only their non-primary loggers, if any). We'll just have to document the potential disk space changes and redis memory usage in release notes / doctext.

afaics we're recommending pcp-zeroconf for everyone, and in case someone has a pmlogger farm of say 20 remote pmcds, there will be a big impact (roughly 6x the storage requirements per logger going from 60s -> 10s logging interval if I'm not missing sth?). Some people might call it a regression, because we're changing behavior which has been there for 6 years.

From my point of view the recent `Requires=pmcd` issue was also a bug. But after fixing it, people who relied on that bug complained, and we reverted it again last-minute. I'm fine with both solutions (fix or document the current behavior), just wanted to mention my recent experience with fixing a bug, which caused problems for people relying on that bug :wink:

**Comment by goodwinos** [comment] 2021-05-04 09:17
re: "changing behavior which has been there for 6 years" => viewed as a regression to fix the bug. Any further thoughts anyone?

**Comment by goodwinos** [comment] 2021-06-17 04:18
In addition to `PMLOGGER_INTERVAL` not being set in the environment of secondary loggers, the following are also missing: `PMLOGGER_LOCAL`, `PMLOGGER_MAXPENDING`, `PMLOGGER_CHECK_SKIP_LOGCONF`

`PMLOGGER_CHECK_SKIP_LOGCONF` not being set leaves loggers that are expecting to share a common static config exposed to the (known) race condition where multiple pmlogconfs may write to the same output config file.

I think we should fix the bug and document the possibly extra logging overheads due to `PMLOGGER_INTERVAL`

```
diff --git a/src/pmlogger/pmlogger_check.sh b/src/pmlogger/pmlogger_check.sh
index e3991aebe..3f93952c4 100755
--- a/src/pmlogger/pmlogger_check.sh
+++ b/src/pmlogger/pmlogger_check.sh
@@ -927,9 +927,9 @@ END                         { print m }'`
 
        if [ -z "$pid" -a $START_PMLOGGER = true ]
        then
+           envs=`grep ^PMLOGGER "$PMLOGGERENVS" 2>/dev/null`
            if [ "X$primary" = Xy ]
            then
-               envs=`grep ^PMLOGGER "$PMLOGGERENVS" 2>/dev/null`
                args="-P $args"
                iam=" primary"
                # clean up port-map, just in case
@@ -949,7 +949,6 @@ END                         { print m }'`
                fi
            else
                args="-h $host $args"
-               envs=""
                iam=""
            fi
```

**Comment by natoscott** [comment] 2022-10-13 00:32
This was resolved in PCP v6 via separate logger farm configuration mechanisms.

**Closed by natoscott** 2022-10-13 00:32 UTC
