### ISSUE TITLE
pmproxy returns invalid JSON if one metric is found and the other is not found

### ISSUE THREAD

**Issue by andreasgerstmayr** [performancecopilot/pcp#1122] opened 2020-10-22 15:30 UTC
For example:

```
$ curl 'http://localhost:44322/pmapi/metric?names=disk.dev.read_bytes,abc'
{"context":703457480,"metrics":[{"name":"disk.dev.read_bytes","series":"bdda1aa16e68c25198f10185eaf3859096a86f7a","pmid":"60.0.38","indom":"60.1","type":"u64","sem":"counter","units":"Kbyte","labels":{"agent":"linux","device_type":"block","domainname":"localdomain","hostname":"agerstmayr-thinkpad","indom_name":"per disk","machineid":"6dabb302d60b402dabcc13dc4fd0fab8"},"text-oneline":"per-disk count of bytes read","text-help":"per-disk count of bytes read"}{"context":703457480,"message":"abc traversal failed - Unknown metric name","success":false}
```

Here `{"context":703457480,"message":"abc traversal failed - Unknown metric name","success":false}` is appended to the previous JSON object, which renders the JSON response invalid, and therefore the browser is ignoring the entire response.

This happens when opening a dashboard where some metrics exist, and some don't (for example MS SQL metrics on my local machine ;) - encountered that error while converting the MS SQL dashboard from json to jsonnet).

Related to #1036

**Comment by natoscott** [comment] 2020-10-27 06:23
This is a duplicate of https://github.com/performancecopilot/pcp/issues/1002

**Closed by natoscott** 2020-10-27 06:23 UTC
Labels: pmproxy
