### ISSUE TITLE
Remove dependency on pmcd in pmlogger and pmie service

### ISSUE THREAD

**Issue by andreasgerstmayr** [performancecopilot/pcp#1200] opened 2021-01-20 08:42 UTC
Both `pmlogger.service` and `pmie.service` contain `Wants=pmcd.service`, i.e. a weak dependency on `pmcd.service` resulting in pmcd getting started when pmlogger or pmie is started.

However, pmcd is not required for pmlogger or pmie in every case - it's perfectly valid to connect to a remote pmcd only, without having a local pmcd running.

For context, this requirement came from having lightweight daemons in the container (https://bugzilla.redhat.com/show_bug.cgi?id=1901130). Jan discovered that it's not possible to run pmlogger without pmcd, because pmlogger always activates the pmcd service. But, as explained above, I think it's not a container issue - pmlogger and pmie shouldn't start a local pmcd, because a local pmcd may not be required (it depends on the configuration of these daemons).

**Comment by andreasgerstmayr** [comment] 2021-01-20 08:49
Just noticed @goodwinos explicitly added this dependency in commit https://github.com/performancecopilot/pcp/commit/01e8bb4368e885ab26fb4742f01c3c9514e55062

Hmm...yes, it's required for the default config, but it's not required for every config. Currently it's not possible to have pmlogger without pmcd, which is also not great.

While typing this I remembered there's the option to mask systemd units (https://fedoramagazine.org/systemd-masking-units/). But still, feels more like a workaround than an actual solution.

**Comment by kmcdonell** [comment] 2021-01-20 20:23
@andreasgerstmayr in the container use case, are the "default" control files (for pmie and pmlogger, as referenced in 01e8bb4368e885ab26fb4742f01c3c9514e55062)  in place?
I would prefer that the pmlogger.service and pmie.service do not force pmcd to be started ... and think whoever is installing these "default" control files needs to take responsibility for also ensuring that pmcd is running (it appears to be more of a packaging/config issue than a systemd-dependency issue from where I sit).

**Comment by goodwinos** [comment] 2021-01-21 07:32
IIRC the issue addressed by  01e8bb4 back in june 2020 or so concerned the probe calls made by pmlogconf on virgin installations. Only metrics in (some) DSO PMDAs can be probed using a local context. Without pmcd, pmlogconf failed to properly generate the initial config.default (which is not packaged) and everything fell in a heap until sometime later when pmcd was started and pmlogconf re-run by pmlogger_check when it started pmlogger. In a container without pmcd, one solution may be to build and pre-install an initial config.default.

**Comment by andreasgerstmayr** [comment] 2021-01-21 10:30
> @andreasgerstmayr in the container use case, are the "default" control files (for pmie and pmlogger, as referenced in [01e8bb4](https://github.com/performancecopilot/pcp/commit/01e8bb4368e885ab26fb4742f01c3c9514e55062)) in place?

Yes. The container has pcp-zeroconf installed and runs pmcd, pmie, pmlogger and pmproxy. For some use cases it's desired to  run only pmcd for example, in that case the container will disable the other services from starting. But the container doesn't touch the configs (except setting PMCD_LOCAL=0 to enable accessing pmcd from outside the container). Users can overwrite the configs when starting the container.

> I would prefer that the pmlogger.service and pmie.service do not force pmcd to be started ...

+1

> and think whoever is installing these "default" control files needs to take responsibility for also ensuring that pmcd is running (it appears to be more of a packaging/config issue than a systemd-dependency issue from where I sit).

afaics per default (i.e. after installation of PCP) no service is started on boot. pcp-zeroconf on RHEL enables pmcd, pmlogger and pmie on boot. So it's usually the user who enables the services to run on boot, and if the user forgets to enable pmcd, then..imho..it's a user mistake.

> and everything fell in a heap until sometime later when pmcd was started and pmlogconf re-run by pmlogger_check when it started pmlogger

hm, yeah we want to avoid that :smile: 

> And then a bit of sed -i on /usr/lib/systemd/system/pmlogger*.service to remove the wants=pmcd stuff

I want to avoid that, I'm not a fan of using sed to regex-replace files. For example if the unit changes to use Requires=pmcd.service at some point, it will silently break the container. In case we decide to not change it in master, I'll go with masking the services instead.

@goodwinos has good points re *everything fell in a heap* to not change it.. OTOH, regular users *might* also want to run pmlogger *without* pmcd on bare-metal.

**Comment by kmcdonell** [comment] 2021-01-21 10:43
@goodwinos I understand the motivation here, but I think in the container use case @andreasgerstmayr is referring to config.default is never used, so we don't need to turn pmcd on to create a config.default that will never be used.

Please chime in if this correct.

If it is correct, we have a possible way forward ... namely if NO pmlogger is configured to use config.default, then we don't need to engage with pmlogconf (and hence the local pmcd) to create config.default.
Now the only person AFIAK that is automagically doing this is zeroconf, so it will depend on the order of things being set up there to determine if this approach might be feasible.

I am guessing there is a parallel case over in pmie-land as well.

**Comment by goodwinos** [comment] 2021-01-22 05:56
> @goodwinos I understand the motivation here, but I think in the container use case @andreasgerstmayr is referring to config.default is never used, so we don't need to turn pmcd on to create a config.default that will never be used.
> 
> Please chime in if this correct.

so the use case is a container with pmlogger logging a remote host (well, not the container itself) and that remote host will have pmcd running with PMCD_LOCAL=0. Right? The issue is not really anything to do with "config.default" then. We just want a pmlogger -h hostspec, which could still use pmlogconf -h hostspec -c -q config.default (or any other config.whatever) and the logconf probes will talk to the remote pmcd at hostspec. No primary logger and no local pmcd needed.

> 
> If it is correct, we have a possible way forward ... namely if NO pmlogger is configured to use config.default, then we don't need to engage with pmlogconf (and hence the local pmcd) to create config.default.

yep. And in that case, the wants=pmcd is wrong because it's globally applied to all pmloggers. In any case, if needed, pmlogconf can be avoided by setting PMLOGGER_CHECK_SKIP_LOGCONF=yes in /etc/sysconfig/pmlogger (which the container build script is free to edit).

> Now the only person AFIAK that is automagically doing this is zeroconf, so it will depend on the order of things being set up there to determine if this approach might be feasible.

I think zeroconf is a special case - it's ment for primary logger talking to local pmcd over unix domain. And the packaging %post scriptlets can enable pmcd and primary logger .. as long as they start in the right order, as you said,  so the pmlogconf wont fail. I guess pmlogger_check knows when it's starting the primary .. so it knows to wait for local pmcd before launching the primary in that case.

> 
> I am guessing there is a parallel case over in pmie-land as well.

yep, same.

I wonder if pmcd.service could use Before=pmlogger.service .. afaik it doesn't imply a dependency, just that if both units are started, pmcd will start first. This might be enough to nuke pmlogger's wants=pmcd. Note pmcd.serivice already has Before=zabbix-agent.service and I bet most of the time zabbix isn't enabled, so it should be safe!

**Comment by andreasgerstmayr** [comment] 2021-01-22 10:23
> > @goodwinos I understand the motivation here, but I think in the container use case @andreasgerstmayr is referring to config.default is never used, so we don't need to turn pmcd on to create a config.default that will never be used.
> > Please chime in if this correct.
> 
> so the use case is a container with pmlogger logging a remote host (well, not the container itself) and that remote host will have pmcd running with PMCD_LOCAL=0. Right?

Yes.

> I wonder if pmcd.service could use Before=pmlogger.service .. afaik it doesn't imply a dependency, just that if both units are started, pmcd will start first.

Yes, that's also how I understand it.

> This might be enough to nuke pmlogger's wants=pmcd. Note pmcd.serivice already has Before=zabbix-agent.service and I bet most of the time zabbix isn't enabled, so it should be safe!

Let's queue this change up for after the 5.2.4 release? (imho not a good idea to change it now, in case there is some difficult to reproduce fallout again)

**Comment by natoscott** [comment] 2021-01-25 00:36
> Yes, that's also how I understand it.
> 
> > This might be enough to nuke pmlogger's wants=pmcd. Note pmcd.serivice already has Before=zabbix-agent.service and I bet most of the time zabbix isn't enabled, so it should be safe!

+1

> Let's queue this change up for after the 5.2.4 release? (imho not a good idea to change it now, in case there is some difficult to reproduce fallout again)

Still a couple weeks out from 5.2.4 - I vote for fixing it up now.

**Closed** 2021-02-02 14:05 UTC
