### ISSUE TITLE
Metrics of pcp-pmda-nvidia-gpu are missing help texts.

### ISSUE THREAD

**Issue by kurik** [performancecopilot/pcp#1271] opened 2021-05-10 16:28 UTC
Metrics of pcp-pmda-nvidia-gpu are missing help texts.

The following metrics of pcp-pmda-nvidia-gpu are missing online help texts.
This is output of ```pminfo -t``` filtered to metrics without a help text:
```
nvidia.numcards One-line Help: Error: One-line or help text is not available
nvidia.gpuid One-line Help: Error: One-line or help text is not available
nvidia.cardname One-line Help: Error: One-line or help text is not available
nvidia.busid One-line Help: Error: One-line or help text is not available
nvidia.temp One-line Help: Error: One-line or help text is not available
nvidia.fanspeed One-line Help: Error: One-line or help text is not available
nvidia.perfstate One-line Help: Error: One-line or help text is not available
nvidia.gpuactive One-line Help: Error: One-line or help text is not available
nvidia.memactive One-line Help: Error: One-line or help text is not available
nvidia.memused One-line Help: Error: One-line or help text is not available
nvidia.memtotal One-line Help: Error: One-line or help text is not available
nvidia.memfree One-line Help: Error: One-line or help text is not available
nvidia.proc.samples One-line Help: Error: One-line or help text is not available
nvidia.proc.memused One-line Help: Error: One-line or help text is not available
nvidia.proc.memaccum One-line Help: Error: One-line or help text is not available
nvidia.proc.gpuactive One-line Help: Error: One-line or help text is not available
nvidia.proc.memactive One-line Help: Error: One-line or help text is not available
nvidia.proc.time One-line Help: Error: One-line or help text is not available
```

The following metrics of pcp-pmda-nvidia-gpu are missing full help texts.
This is output of ```pminfo -T``` filtered to metrics without a help text:
```

nvidia.numcards
Full Help: Error: One-line or help text is not available

nvidia.gpuid
Full Help: Error: One-line or help text is not available

nvidia.cardname
Full Help: Error: One-line or help text is not available

nvidia.busid
Full Help: Error: One-line or help text is not available

nvidia.temp
Full Help: Error: One-line or help text is not available

nvidia.fanspeed
Full Help: Error: One-line or help text is not available

nvidia.perfstate
Full Help: Error: One-line or help text is not available

nvidia.gpuactive
Full Help: Error: One-line or help text is not available

nvidia.memactive
Full Help: Error: One-line or help text is not available

nvidia.memused
Full Help: Error: One-line or help text is not available

nvidia.memtotal
Full Help: Error: One-line or help text is not available

nvidia.memfree
Full Help: Error: One-line or help text is not available

nvidia.proc.samples
Full Help: Error: One-line or help text is not available

nvidia.proc.memused
Full Help: Error: One-line or help text is not available

nvidia.proc.memaccum
Full Help: Error: One-line or help text is not available

nvidia.proc.gpuactive
Full Help: Error: One-line or help text is not available

nvidia.proc.memactive
Full Help: Error: One-line or help text is not available

nvidia.proc.time
Full Help: Error: One-line or help text is not available
```

**Comment by kmcdonell** [comment] 2023-05-10 21:41
This issue is not understood, but it is not apparently reproducible.  The help text files for this PMDA are packaged and installed and appear to be available once the PMDA is in use by pmcd(1).
Closing the issue, please re-open if the problem is observed again.

**Closed by kmcdonell** 2023-05-10 21:41 UTC
