### ISSUE TITLE
Metrics of pcp-pmda-elasticsearch are missing help texts.

### ISSUE THREAD

**Issue by kurik** [performancecopilot/pcp#1260] opened 2021-05-10 15:10 UTC
Metrics of pcp-pmda-elasticsearch are missing help texts.

The following metrics of pcp-pmda-elasticsearch are missing online help texts.
This is output of ```pminfo -t``` filtered to metrics without a help text:
```
elasticsearch.nodes.http.total_opened []
elasticsearch.nodes.http.current_open []
elasticsearch.nodes.transport.tx_size_in_bytes []
elasticsearch.nodes.transport.tx_count []
elasticsearch.nodes.transport.rx_size_in_bytes []
elasticsearch.nodes.transport.rx_count []
elasticsearch.nodes.transport.server_open []
elasticsearch.nodes.process.max_file_descriptors []
elasticsearch.nodes.process.mem.total_virtual_in_bytes []
elasticsearch.nodes.process.mem.resident_in_bytes []
elasticsearch.nodes.process.cpu.user_in_millis []
elasticsearch.nodes.process.cpu.sys_in_millis []
elasticsearch.nodes.process.cpu.percent []
elasticsearch.nodes.process.open_file_descriptors []
elasticsearch.nodes.process.timestamp []
elasticsearch.nodes.jvm.vm_version []
elasticsearch.nodes.jvm.vm_name []
elasticsearch.nodes.jvm.version []
elasticsearch.nodes.jvm.pid []
elasticsearch.nodes.jvm.gc.collectors.ConcurrentMarkSweep.collection_time_in_millis []
elasticsearch.nodes.jvm.gc.collectors.ConcurrentMarkSweep.collection_count []
elasticsearch.nodes.jvm.gc.collectors.ParNew.collection_time_in_millis []
elasticsearch.nodes.jvm.gc.collectors.ParNew.collection_count []
elasticsearch.nodes.jvm.gc.collectors.Copy.collection_time_in_millis []
elasticsearch.nodes.jvm.gc.collectors.Copy.collection_count []
elasticsearch.nodes.jvm.gc.collection_time_in_millis []
elasticsearch.nodes.jvm.gc.collection_count []
elasticsearch.nodes.jvm.threads.peak_count []
elasticsearch.nodes.jvm.threads.count []
elasticsearch.nodes.jvm.mem.non_heap_max_in_bytes []
elasticsearch.nodes.jvm.mem.non_heap_init_in_bytes []
elasticsearch.nodes.jvm.mem.heap_max_in_bytes []
elasticsearch.nodes.jvm.mem.heap_init_in_bytes []
elasticsearch.nodes.jvm.mem.non_heap_committed_in_bytes []
elasticsearch.nodes.jvm.mem.non_heap_used_in_bytes []
elasticsearch.nodes.jvm.mem.heap_committed_in_bytes []
elasticsearch.nodes.jvm.mem.heap_used_in_bytes []
elasticsearch.nodes.jvm.uptime []
elasticsearch.nodes.jvm.uptime_in_millis []
elasticsearch.nodes.indices.search.fetch_time_in_millis []
elasticsearch.nodes.indices.search.fetch_total []
elasticsearch.nodes.indices.search.query_time_in_millis []
elasticsearch.nodes.indices.search.query_total []
elasticsearch.nodes.indices.get.missing_time_in_millis []
elasticsearch.nodes.indices.get.missing_total []
elasticsearch.nodes.indices.get.exists_time_in_millis []
elasticsearch.nodes.indices.get.exists_total []
elasticsearch.nodes.indices.get.time_in_millis []
elasticsearch.nodes.indices.get.total []
elasticsearch.nodes.indices.store.size_in_bytes []
elasticsearch.nodes.indices.flush.total_time_in_millis []
elasticsearch.nodes.indices.flush.total []
elasticsearch.nodes.indices.refresh.total_time_in_millis []
elasticsearch.nodes.indices.refresh.total []
elasticsearch.nodes.indices.indexing.delete_time_in_millis []
elasticsearch.nodes.indices.indexing.delete_total []
elasticsearch.nodes.indices.indexing.index_time_in_millis []
elasticsearch.nodes.indices.indexing.index_total []
elasticsearch.nodes.indices.merges.total_size_in_bytes []
elasticsearch.nodes.indices.merges.total_docs []
elasticsearch.nodes.indices.merges.current_size_in_bytes []
elasticsearch.nodes.indices.merges.current_docs []
elasticsearch.nodes.indices.merges.total_time_in_millis []
elasticsearch.nodes.indices.merges.total []
elasticsearch.nodes.indices.merges.current []
elasticsearch.nodes.indices.cache.filter_size_in_bytes []
elasticsearch.nodes.indices.cache.filter_evictions []
elasticsearch.nodes.indices.cache.filter_count []
elasticsearch.nodes.indices.cache.field_size_in_bytes []
elasticsearch.nodes.indices.cache.field_evictions []
elasticsearch.nodes.indices.docs.deleted []
elasticsearch.nodes.indices.docs.num_docs []
elasticsearch.nodes.indices.docs.count []
elasticsearch.nodes.indices.size_in_bytes []
```

The following metrics of pcp-pmda-elasticsearch are missing full help texts.
This is output of ```pminfo -T``` filtered to metrics without a help text:
```

elasticsearch.nodes.http.total_opened
Help: <empty entry>

elasticsearch.nodes.http.current_open
Help: <empty entry>

elasticsearch.nodes.transport.tx_size_in_bytes
Help: <empty entry>

elasticsearch.nodes.transport.tx_count
Help: <empty entry>

elasticsearch.nodes.transport.rx_size_in_bytes
Help: <empty entry>

elasticsearch.nodes.transport.rx_count
Help: <empty entry>

elasticsearch.nodes.transport.server_open
Help: <empty entry>

elasticsearch.nodes.process.max_file_descriptors
Help: <empty entry>

elasticsearch.nodes.process.mem.total_virtual_in_bytes
Help: <empty entry>

elasticsearch.nodes.process.mem.resident_in_bytes
Help: <empty entry>

elasticsearch.nodes.process.cpu.user_in_millis
Help: <empty entry>

elasticsearch.nodes.process.cpu.sys_in_millis
Help: <empty entry>

elasticsearch.nodes.process.cpu.percent
Help: <empty entry>

elasticsearch.nodes.process.open_file_descriptors
Help: <empty entry>

elasticsearch.nodes.process.timestamp
Help: <empty entry>

elasticsearch.nodes.jvm.vm_version
Help: <empty entry>

elasticsearch.nodes.jvm.vm_name
Help: <empty entry>

elasticsearch.nodes.jvm.version
Help: <empty entry>

elasticsearch.nodes.jvm.pid
Help: <empty entry>

elasticsearch.nodes.jvm.gc.collectors.ConcurrentMarkSweep.collection_time_in_millis
Help: <empty entry>

elasticsearch.nodes.jvm.gc.collectors.ConcurrentMarkSweep.collection_count
Help: <empty entry>

elasticsearch.nodes.jvm.gc.collectors.ParNew.collection_time_in_millis
Help: <empty entry>

elasticsearch.nodes.jvm.gc.collectors.ParNew.collection_count
Help: <empty entry>

elasticsearch.nodes.jvm.gc.collectors.Copy.collection_time_in_millis
Help: <empty entry>

elasticsearch.nodes.jvm.gc.collectors.Copy.collection_count
Help: <empty entry>

elasticsearch.nodes.jvm.gc.collection_time_in_millis
Help: <empty entry>

elasticsearch.nodes.jvm.gc.collection_count
Help: <empty entry>

elasticsearch.nodes.jvm.threads.peak_count
Help: <empty entry>

elasticsearch.nodes.jvm.threads.count
Help: <empty entry>

elasticsearch.nodes.jvm.mem.non_heap_max_in_bytes
Help: <empty entry>

elasticsearch.nodes.jvm.mem.non_heap_init_in_bytes
Help: <empty entry>

elasticsearch.nodes.jvm.mem.heap_max_in_bytes
Help: <empty entry>

elasticsearch.nodes.jvm.mem.heap_init_in_bytes
Help: <empty entry>

elasticsearch.nodes.jvm.mem.non_heap_committed_in_bytes
Help: <empty entry>

elasticsearch.nodes.jvm.mem.non_heap_used_in_bytes
Help: <empty entry>

elasticsearch.nodes.jvm.mem.heap_committed_in_bytes
Help: <empty entry>

elasticsearch.nodes.jvm.mem.heap_used_in_bytes
Help: <empty entry>

elasticsearch.nodes.jvm.uptime
Help: <empty entry>

elasticsearch.nodes.jvm.uptime_in_millis
Help: <empty entry>

elasticsearch.nodes.indices.search.fetch_time_in_millis
Help: <empty entry>

elasticsearch.nodes.indices.search.fetch_total
Help: <empty entry>

elasticsearch.nodes.indices.search.query_time_in_millis
Help: <empty entry>

elasticsearch.nodes.indices.search.query_total
Help: <empty entry>

elasticsearch.nodes.indices.get.missing_time_in_millis
Help: <empty entry>

elasticsearch.nodes.indices.get.missing_total
Help: <empty entry>

elasticsearch.nodes.indices.get.exists_time_in_millis
Help: <empty entry>

elasticsearch.nodes.indices.get.exists_total
Help: <empty entry>

elasticsearch.nodes.indices.get.time_in_millis
Help: <empty entry>

elasticsearch.nodes.indices.get.total
Help: <empty entry>

elasticsearch.nodes.indices.store.size_in_bytes
Help: <empty entry>

elasticsearch.nodes.indices.flush.total_time_in_millis
Help: <empty entry>

elasticsearch.nodes.indices.flush.total
Help: <empty entry>

elasticsearch.nodes.indices.refresh.total_time_in_millis
Help: <empty entry>

elasticsearch.nodes.indices.refresh.total
Help: <empty entry>

elasticsearch.nodes.indices.indexing.delete_time_in_millis
Help: <empty entry>

elasticsearch.nodes.indices.indexing.delete_total
Help: <empty entry>

elasticsearch.nodes.indices.indexing.index_time_in_millis
Help: <empty entry>

elasticsearch.nodes.indices.indexing.index_total
Help: <empty entry>

elasticsearch.nodes.indices.merges.total_size_in_bytes
Help: <empty entry>

elasticsearch.nodes.indices.merges.total_docs
Help: <empty entry>

elasticsearch.nodes.indices.merges.current_size_in_bytes
Help: <empty entry>

elasticsearch.nodes.indices.merges.current_docs
Help: <empty entry>

elasticsearch.nodes.indices.merges.total_time_in_millis
Help: <empty entry>

elasticsearch.nodes.indices.merges.total
Help: <empty entry>

elasticsearch.nodes.indices.merges.current
Help: <empty entry>

elasticsearch.nodes.indices.cache.filter_size_in_bytes
Help: <empty entry>

elasticsearch.nodes.indices.cache.filter_evictions
Help: <empty entry>

elasticsearch.nodes.indices.cache.filter_count
Help: <empty entry>

elasticsearch.nodes.indices.cache.field_size_in_bytes
Help: <empty entry>

elasticsearch.nodes.indices.cache.field_evictions
Help: <empty entry>

elasticsearch.nodes.indices.docs.deleted
Help: <empty entry>

elasticsearch.nodes.indices.docs.num_docs
Help: <empty entry>

elasticsearch.nodes.indices.docs.count
Help: <empty entry>

elasticsearch.nodes.indices.size_in_bytes
Help: <empty entry>
```

**Comment by kmcdonell** [comment] 2023-05-10 21:56
This issue is not understood, but it is not apparently reproducible.  The help text files for this PMDA are packaged and installed and appear to be available once the PMDA is in use by pmcd(1).
Closing the issue, please re-open if the problem is observed again.

**Closed** 2023-05-10 21:57 UTC
