### ISSUE TITLE
Metrics of pcp-pmda-news are missing help texts.

### ISSUE THREAD

**Issue by kurik** [performancecopilot/pcp#1270] opened 2021-05-10 16:28 UTC
Metrics of pcp-pmda-news are missing help texts.

The following metrics of pcp-pmda-news are missing online help texts.
This is output of ```pminfo -t``` filtered to metrics without a help text:
```
news.articles.last []
news.readers.vn []
news.readers.rn []
news.readers.xrn []
news.readers.trn []
news.readers.nnrpd []
```

The following metrics of pcp-pmda-news are missing full help texts.
This is output of ```pminfo -T``` filtered to metrics without a help text:
```

news.articles.last
Help: <empty entry>

news.readers.vn
Help: <empty entry>

news.readers.rn
Help: <empty entry>

news.readers.xrn
Help: <empty entry>

news.readers.trn
Help: <empty entry>

news.readers.nnrpd
Help: <empty entry>
```

**Comment by kmcdonell** [comment] 2023-05-10 22:00
This issue is not understood, but it is not apparently reproducible.  The help text files for this PMDA are packaged and installed and appear to be available once the PMDA is in use by pmcd(1).
Closing the issue, please re-open if the problem is observed again.

**Closed by kmcdonell** 2023-05-10 22:00 UTC
