### ISSUE TITLE
Metrics of pcp-pmda-mailq are missing help texts.

### ISSUE THREAD

**Issue by kurik** [performancecopilot/pcp#1266] opened 2021-05-10 16:24 UTC
Metrics of pcp-pmda-mailq are missing help texts.

The following metrics of pcp-pmda-mailq are missing online help texts.
This is output of ```pminfo -t``` filtered to metrics without a help text:
```
mailq.length One-line Help: Error: One-line or help text is not available
mailq.deferred One-line Help: Error: One-line or help text is not available
```

The following metrics of pcp-pmda-mailq are missing full help texts.
This is output of ```pminfo -T``` filtered to metrics without a help text:
```

mailq.length
Full Help: Error: One-line or help text is not available

mailq.deferred
Full Help: Error: One-line or help text is not available
```

**Comment by kmcdonell** [comment] 2023-05-10 21:44
This issue is not understood, but it is not apparently reproducible.  The help text files for this PMDA are packaged and installed and appear to be available once the PMDA is in use by pmcd(1).
Closing the issue, please re-open if the problem is observed again.

**Closed by kmcdonell** 2023-05-10 21:44 UTC
