### ISSUE TITLE
Metrics of pcp-pmda-weblog are missing help texts.

### ISSUE THREAD

**Issue by kurik** [performancecopilot/pcp#1282] opened 2021-05-10 16:33 UTC
Metrics of pcp-pmda-weblog are missing help texts.

The following metrics of pcp-pmda-weblog are missing online help texts.
This is output of ```pminfo -t``` filtered to metrics without a help text:
```
web.config.numservers One-line Help: Error: One-line or help text is not available
web.config.catchup One-line Help: Error: One-line or help text is not available
web.config.catchuptime One-line Help: Error: One-line or help text is not available
web.config.check One-line Help: Error: One-line or help text is not available
web.allservers.numwatched One-line Help: Error: One-line or help text is not available
web.allservers.numalive One-line Help: Error: One-line or help text is not available
web.allservers.errors One-line Help: Error: One-line or help text is not available
web.allservers.requests.total One-line Help: Error: One-line or help text is not available
web.allservers.requests.get One-line Help: Error: One-line or help text is not available
web.allservers.requests.head One-line Help: Error: One-line or help text is not available
web.allservers.requests.post One-line Help: Error: One-line or help text is not available
web.allservers.requests.other One-line Help: Error: One-line or help text is not available
web.allservers.requests.size.zero One-line Help: Error: One-line or help text is not available
web.allservers.requests.size.le3k One-line Help: Error: One-line or help text is not available
web.allservers.requests.size.le10k One-line Help: Error: One-line or help text is not available
web.allservers.requests.size.le30k One-line Help: Error: One-line or help text is not available
web.allservers.requests.size.le100k One-line Help: Error: One-line or help text is not available
web.allservers.requests.size.le300k One-line Help: Error: One-line or help text is not available
web.allservers.requests.size.le1m One-line Help: Error: One-line or help text is not available
web.allservers.requests.size.le3m One-line Help: Error: One-line or help text is not available
web.allservers.requests.size.gt3m One-line Help: Error: One-line or help text is not available
web.allservers.requests.size.unknown One-line Help: Error: One-line or help text is not available
web.allservers.requests.client.total One-line Help: Error: One-line or help text is not available
web.allservers.requests.cached.total One-line Help: Error: One-line or help text is not available
web.allservers.requests.cached.size.zero One-line Help: Error: One-line or help text is not available
web.allservers.requests.cached.size.le3k One-line Help: Error: One-line or help text is not available
web.allservers.requests.cached.size.le10k One-line Help: Error: One-line or help text is not available
web.allservers.requests.cached.size.le30k One-line Help: Error: One-line or help text is not available
web.allservers.requests.cached.size.le100k One-line Help: Error: One-line or help text is not available
web.allservers.requests.cached.size.le300k One-line Help: Error: One-line or help text is not available
web.allservers.requests.cached.size.le1m One-line Help: Error: One-line or help text is not available
web.allservers.requests.cached.size.le3m One-line Help: Error: One-line or help text is not available
web.allservers.requests.cached.size.gt3m One-line Help: Error: One-line or help text is not available
web.allservers.requests.cached.size.unknown One-line Help: Error: One-line or help text is not available
web.allservers.requests.uncached.total One-line Help: Error: One-line or help text is not available
web.allservers.requests.uncached.size.zero One-line Help: Error: One-line or help text is not available
web.allservers.requests.uncached.size.le3k One-line Help: Error: One-line or help text is not available
web.allservers.requests.uncached.size.le10k One-line Help: Error: One-line or help text is not available
web.allservers.requests.uncached.size.le30k One-line Help: Error: One-line or help text is not available
web.allservers.requests.uncached.size.le100k One-line Help: Error: One-line or help text is not available
web.allservers.requests.uncached.size.le300k One-line Help: Error: One-line or help text is not available
web.allservers.requests.uncached.size.le1m One-line Help: Error: One-line or help text is not available
web.allservers.requests.uncached.size.le3m One-line Help: Error: One-line or help text is not available
web.allservers.requests.uncached.size.gt3m One-line Help: Error: One-line or help text is not available
web.allservers.requests.uncached.size.unknown One-line Help: Error: One-line or help text is not available
web.allservers.bytes.total One-line Help: Error: One-line or help text is not available
web.allservers.bytes.get One-line Help: Error: One-line or help text is not available
web.allservers.bytes.head One-line Help: Error: One-line or help text is not available
web.allservers.bytes.post One-line Help: Error: One-line or help text is not available
web.allservers.bytes.other One-line Help: Error: One-line or help text is not available
web.allservers.bytes.size.zero One-line Help: Error: One-line or help text is not available
web.allservers.bytes.size.le3k One-line Help: Error: One-line or help text is not available
web.allservers.bytes.size.le10k One-line Help: Error: One-line or help text is not available
web.allservers.bytes.size.le30k One-line Help: Error: One-line or help text is not available
web.allservers.bytes.size.le100k One-line Help: Error: One-line or help text is not available
web.allservers.bytes.size.le300k One-line Help: Error: One-line or help text is not available
web.allservers.bytes.size.le1m One-line Help: Error: One-line or help text is not available
web.allservers.bytes.size.le3m One-line Help: Error: One-line or help text is not available
web.allservers.bytes.size.gt3m One-line Help: Error: One-line or help text is not available
web.allservers.bytes.cached.total One-line Help: Error: One-line or help text is not available
web.allservers.bytes.cached.size.zero One-line Help: Error: One-line or help text is not available
web.allservers.bytes.cached.size.le3k One-line Help: Error: One-line or help text is not available
web.allservers.bytes.cached.size.le10k One-line Help: Error: One-line or help text is not available
web.allservers.bytes.cached.size.le30k One-line Help: Error: One-line or help text is not available
web.allservers.bytes.cached.size.le100k One-line Help: Error: One-line or help text is not available
web.allservers.bytes.cached.size.le300k One-line Help: Error: One-line or help text is not available
web.allservers.bytes.cached.size.le1m One-line Help: Error: One-line or help text is not available
web.allservers.bytes.cached.size.le3m One-line Help: Error: One-line or help text is not available
web.allservers.bytes.cached.size.gt3m One-line Help: Error: One-line or help text is not available
web.allservers.bytes.uncached.total One-line Help: Error: One-line or help text is not available
web.allservers.bytes.uncached.size.zero One-line Help: Error: One-line or help text is not available
web.allservers.bytes.uncached.size.le3k One-line Help: Error: One-line or help text is not available
web.allservers.bytes.uncached.size.le10k One-line Help: Error: One-line or help text is not available
web.allservers.bytes.uncached.size.le30k One-line Help: Error: One-line or help text is not available
web.allservers.bytes.uncached.size.le100k One-line Help: Error: One-line or help text is not available
web.allservers.bytes.uncached.size.le300k One-line Help: Error: One-line or help text is not available
web.allservers.bytes.uncached.size.le1m One-line Help: Error: One-line or help text is not available
web.allservers.bytes.uncached.size.le3m One-line Help: Error: One-line or help text is not available
web.allservers.bytes.uncached.size.gt3m One-line Help: Error: One-line or help text is not available
web.perserver.watched One-line Help: Error: One-line or help text is not available
web.perserver.numlogs One-line Help: Error: One-line or help text is not available
web.perserver.errors One-line Help: Error: One-line or help text is not available
web.perserver.logidletime One-line Help: Error: One-line or help text is not available
web.perserver.requests.total One-line Help: Error: One-line or help text is not available
web.perserver.requests.get One-line Help: Error: One-line or help text is not available
web.perserver.requests.head One-line Help: Error: One-line or help text is not available
web.perserver.requests.post One-line Help: Error: One-line or help text is not available
web.perserver.requests.other One-line Help: Error: One-line or help text is not available
web.perserver.requests.size.zero One-line Help: Error: One-line or help text is not available
web.perserver.requests.size.le3k One-line Help: Error: One-line or help text is not available
web.perserver.requests.size.le10k One-line Help: Error: One-line or help text is not available
web.perserver.requests.size.le30k One-line Help: Error: One-line or help text is not available
web.perserver.requests.size.le100k One-line Help: Error: One-line or help text is not available
web.perserver.requests.size.le300k One-line Help: Error: One-line or help text is not available
web.perserver.requests.size.le1m One-line Help: Error: One-line or help text is not available
web.perserver.requests.size.le3m One-line Help: Error: One-line or help text is not available
web.perserver.requests.size.gt3m One-line Help: Error: One-line or help text is not available
web.perserver.requests.size.unknown One-line Help: Error: One-line or help text is not available
web.perserver.requests.client.total One-line Help: Error: One-line or help text is not available
web.perserver.requests.cached.total One-line Help: Error: One-line or help text is not available
web.perserver.requests.cached.size.zero One-line Help: Error: One-line or help text is not available
web.perserver.requests.cached.size.le3k One-line Help: Error: One-line or help text is not available
web.perserver.requests.cached.size.le10k One-line Help: Error: One-line or help text is not available
web.perserver.requests.cached.size.le30k One-line Help: Error: One-line or help text is not available
web.perserver.requests.cached.size.le100k One-line Help: Error: One-line or help text is not available
web.perserver.requests.cached.size.le300k One-line Help: Error: One-line or help text is not available
web.perserver.requests.cached.size.le1m One-line Help: Error: One-line or help text is not available
web.perserver.requests.cached.size.le3m One-line Help: Error: One-line or help text is not available
web.perserver.requests.cached.size.gt3m One-line Help: Error: One-line or help text is not available
web.perserver.requests.cached.size.unknown One-line Help: Error: One-line or help text is not available
web.perserver.requests.uncached.total One-line Help: Error: One-line or help text is not available
web.perserver.requests.uncached.size.zero One-line Help: Error: One-line or help text is not available
web.perserver.requests.uncached.size.le3k One-line Help: Error: One-line or help text is not available
web.perserver.requests.uncached.size.le10k One-line Help: Error: One-line or help text is not available
web.perserver.requests.uncached.size.le30k One-line Help: Error: One-line or help text is not available
web.perserver.requests.uncached.size.le100k One-line Help: Error: One-line or help text is not available
web.perserver.requests.uncached.size.le300k One-line Help: Error: One-line or help text is not available
web.perserver.requests.uncached.size.le1m One-line Help: Error: One-line or help text is not available
web.perserver.requests.uncached.size.le3m One-line Help: Error: One-line or help text is not available
web.perserver.requests.uncached.size.gt3m One-line Help: Error: One-line or help text is not available
web.perserver.requests.uncached.size.unknown One-line Help: Error: One-line or help text is not available
web.perserver.bytes.total One-line Help: Error: One-line or help text is not available
web.perserver.bytes.get One-line Help: Error: One-line or help text is not available
web.perserver.bytes.head One-line Help: Error: One-line or help text is not available
web.perserver.bytes.post One-line Help: Error: One-line or help text is not available
web.perserver.bytes.other One-line Help: Error: One-line or help text is not available
web.perserver.bytes.size.zero One-line Help: Error: One-line or help text is not available
web.perserver.bytes.size.le3k One-line Help: Error: One-line or help text is not available
web.perserver.bytes.size.le10k One-line Help: Error: One-line or help text is not available
web.perserver.bytes.size.le30k One-line Help: Error: One-line or help text is not available
web.perserver.bytes.size.le100k One-line Help: Error: One-line or help text is not available
web.perserver.bytes.size.le300k One-line Help: Error: One-line or help text is not available
web.perserver.bytes.size.le1m One-line Help: Error: One-line or help text is not available
web.perserver.bytes.size.le3m One-line Help: Error: One-line or help text is not available
web.perserver.bytes.size.gt3m One-line Help: Error: One-line or help text is not available
web.perserver.bytes.cached.total One-line Help: Error: One-line or help text is not available
web.perserver.bytes.cached.size.zero One-line Help: Error: One-line or help text is not available
web.perserver.bytes.cached.size.le3k One-line Help: Error: One-line or help text is not available
web.perserver.bytes.cached.size.le10k One-line Help: Error: One-line or help text is not available
web.perserver.bytes.cached.size.le30k One-line Help: Error: One-line or help text is not available
web.perserver.bytes.cached.size.le100k One-line Help: Error: One-line or help text is not available
web.perserver.bytes.cached.size.le300k One-line Help: Error: One-line or help text is not available
web.perserver.bytes.cached.size.le1m One-line Help: Error: One-line or help text is not available
web.perserver.bytes.cached.size.le3m One-line Help: Error: One-line or help text is not available
web.perserver.bytes.cached.size.gt3m One-line Help: Error: One-line or help text is not available
web.perserver.bytes.uncached.total One-line Help: Error: One-line or help text is not available
web.perserver.bytes.uncached.size.zero One-line Help: Error: One-line or help text is not available
web.perserver.bytes.uncached.size.le3k One-line Help: Error: One-line or help text is not available
web.perserver.bytes.uncached.size.le10k One-line Help: Error: One-line or help text is not available
web.perserver.bytes.uncached.size.le30k One-line Help: Error: One-line or help text is not available
web.perserver.bytes.uncached.size.le100k One-line Help: Error: One-line or help text is not available
web.perserver.bytes.uncached.size.le300k One-line Help: Error: One-line or help text is not available
web.perserver.bytes.uncached.size.le1m One-line Help: Error: One-line or help text is not available
web.perserver.bytes.uncached.size.le3m One-line Help: Error: One-line or help text is not available
web.perserver.bytes.uncached.size.gt3m One-line Help: Error: One-line or help text is not available
```

The following metrics of pcp-pmda-weblog are missing full help texts.
This is output of ```pminfo -T``` filtered to metrics without a help text:
```

web.config.numservers
Full Help: Error: One-line or help text is not available

web.config.catchup
Full Help: Error: One-line or help text is not available

web.config.catchuptime
Full Help: Error: One-line or help text is not available

web.config.check
Full Help: Error: One-line or help text is not available

web.allservers.numwatched
Full Help: Error: One-line or help text is not available

web.allservers.numalive
Full Help: Error: One-line or help text is not available

web.allservers.errors
Full Help: Error: One-line or help text is not available

web.allservers.requests.total
Full Help: Error: One-line or help text is not available

web.allservers.requests.get
Full Help: Error: One-line or help text is not available

web.allservers.requests.head
Full Help: Error: One-line or help text is not available

web.allservers.requests.post
Full Help: Error: One-line or help text is not available

web.allservers.requests.other
Full Help: Error: One-line or help text is not available

web.allservers.requests.size.zero
Full Help: Error: One-line or help text is not available

web.allservers.requests.size.le3k
Full Help: Error: One-line or help text is not available

web.allservers.requests.size.le10k
Full Help: Error: One-line or help text is not available

web.allservers.requests.size.le30k
Full Help: Error: One-line or help text is not available

web.allservers.requests.size.le100k
Full Help: Error: One-line or help text is not available

web.allservers.requests.size.le300k
Full Help: Error: One-line or help text is not available

web.allservers.requests.size.le1m
Full Help: Error: One-line or help text is not available

web.allservers.requests.size.le3m
Full Help: Error: One-line or help text is not available

web.allservers.requests.size.gt3m
Full Help: Error: One-line or help text is not available

web.allservers.requests.size.unknown
Full Help: Error: One-line or help text is not available

web.allservers.requests.client.total
Full Help: Error: One-line or help text is not available

web.allservers.requests.cached.total
Full Help: Error: One-line or help text is not available

web.allservers.requests.cached.size.zero
Full Help: Error: One-line or help text is not available

web.allservers.requests.cached.size.le3k
Full Help: Error: One-line or help text is not available

web.allservers.requests.cached.size.le10k
Full Help: Error: One-line or help text is not available

web.allservers.requests.cached.size.le30k
Full Help: Error: One-line or help text is not available

web.allservers.requests.cached.size.le100k
Full Help: Error: One-line or help text is not available

web.allservers.requests.cached.size.le300k
Full Help: Error: One-line or help text is not available

web.allservers.requests.cached.size.le1m
Full Help: Error: One-line or help text is not available

web.allservers.requests.cached.size.le3m
Full Help: Error: One-line or help text is not available

web.allservers.requests.cached.size.gt3m
Full Help: Error: One-line or help text is not available

web.allservers.requests.cached.size.unknown
Full Help: Error: One-line or help text is not available

web.allservers.requests.uncached.total
Full Help: Error: One-line or help text is not available

web.allservers.requests.uncached.size.zero
Full Help: Error: One-line or help text is not available

web.allservers.requests.uncached.size.le3k
Full Help: Error: One-line or help text is not available

web.allservers.requests.uncached.size.le10k
Full Help: Error: One-line or help text is not available

web.allservers.requests.uncached.size.le30k
Full Help: Error: One-line or help text is not available

web.allservers.requests.uncached.size.le100k
Full Help: Error: One-line or help text is not available

web.allservers.requests.uncached.size.le300k
Full Help: Error: One-line or help text is not available

web.allservers.requests.uncached.size.le1m
Full Help: Error: One-line or help text is not available

web.allservers.requests.uncached.size.le3m
Full Help: Error: One-line or help text is not available

web.allservers.requests.uncached.size.gt3m
Full Help: Error: One-line or help text is not available

web.allservers.requests.uncached.size.unknown
Full Help: Error: One-line or help text is not available

web.allservers.bytes.total
Full Help: Error: One-line or help text is not available

web.allservers.bytes.get
Full Help: Error: One-line or help text is not available

web.allservers.bytes.head
Full Help: Error: One-line or help text is not available

web.allservers.bytes.post
Full Help: Error: One-line or help text is not available

web.allservers.bytes.other
Full Help: Error: One-line or help text is not available

web.allservers.bytes.size.zero
Full Help: Error: One-line or help text is not available

web.allservers.bytes.size.le3k
Full Help: Error: One-line or help text is not available

web.allservers.bytes.size.le10k
Full Help: Error: One-line or help text is not available

web.allservers.bytes.size.le30k
Full Help: Error: One-line or help text is not available

web.allservers.bytes.size.le100k
Full Help: Error: One-line or help text is not available

web.allservers.bytes.size.le300k
Full Help: Error: One-line or help text is not available

web.allservers.bytes.size.le1m
Full Help: Error: One-line or help text is not available

web.allservers.bytes.size.le3m
Full Help: Error: One-line or help text is not available

web.allservers.bytes.size.gt3m
Full Help: Error: One-line or help text is not available

web.allservers.bytes.cached.total
Full Help: Error: One-line or help text is not available

web.allservers.bytes.cached.size.zero
Full Help: Error: One-line or help text is not available

web.allservers.bytes.cached.size.le3k
Full Help: Error: One-line or help text is not available

web.allservers.bytes.cached.size.le10k
Full Help: Error: One-line or help text is not available

web.allservers.bytes.cached.size.le30k
Full Help: Error: One-line or help text is not available

web.allservers.bytes.cached.size.le100k
Full Help: Error: One-line or help text is not available

web.allservers.bytes.cached.size.le300k
Full Help: Error: One-line or help text is not available

web.allservers.bytes.cached.size.le1m
Full Help: Error: One-line or help text is not available

web.allservers.bytes.cached.size.le3m
Full Help: Error: One-line or help text is not available

web.allservers.bytes.cached.size.gt3m
Full Help: Error: One-line or help text is not available

web.allservers.bytes.uncached.total
Full Help: Error: One-line or help text is not available

web.allservers.bytes.uncached.size.zero
Full Help: Error: One-line or help text is not available

web.allservers.bytes.uncached.size.le3k
Full Help: Error: One-line or help text is not available

web.allservers.bytes.uncached.size.le10k
Full Help: Error: One-line or help text is not available

web.allservers.bytes.uncached.size.le30k
Full Help: Error: One-line or help text is not available

web.allservers.bytes.uncached.size.le100k
Full Help: Error: One-line or help text is not available

web.allservers.bytes.uncached.size.le300k
Full Help: Error: One-line or help text is not available

web.allservers.bytes.uncached.size.le1m
Full Help: Error: One-line or help text is not available

web.allservers.bytes.uncached.size.le3m
Full Help: Error: One-line or help text is not available

web.allservers.bytes.uncached.size.gt3m
Full Help: Error: One-line or help text is not available

web.perserver.watched
Full Help: Error: One-line or help text is not available

web.perserver.numlogs
Full Help: Error: One-line or help text is not available

web.perserver.errors
Full Help: Error: One-line or help text is not available

web.perserver.logidletime
Full Help: Error: One-line or help text is not available

web.perserver.requests.total
Full Help: Error: One-line or help text is not available

web.perserver.requests.get
Full Help: Error: One-line or help text is not available

web.perserver.requests.head
Full Help: Error: One-line or help text is not available

web.perserver.requests.post
Full Help: Error: One-line or help text is not available

web.perserver.requests.other
Full Help: Error: One-line or help text is not available

web.perserver.requests.size.zero
Full Help: Error: One-line or help text is not available

web.perserver.requests.size.le3k
Full Help: Error: One-line or help text is not available

web.perserver.requests.size.le10k
Full Help: Error: One-line or help text is not available

web.perserver.requests.size.le30k
Full Help: Error: One-line or help text is not available

web.perserver.requests.size.le100k
Full Help: Error: One-line or help text is not available

web.perserver.requests.size.le300k
Full Help: Error: One-line or help text is not available

web.perserver.requests.size.le1m
Full Help: Error: One-line or help text is not available

web.perserver.requests.size.le3m
Full Help: Error: One-line or help text is not available

web.perserver.requests.size.gt3m
Full Help: Error: One-line or help text is not available

web.perserver.requests.size.unknown
Full Help: Error: One-line or help text is not available

web.perserver.requests.client.total
Full Help: Error: One-line or help text is not available

web.perserver.requests.cached.total
Full Help: Error: One-line or help text is not available

web.perserver.requests.cached.size.zero
Full Help: Error: One-line or help text is not available

web.perserver.requests.cached.size.le3k
Full Help: Error: One-line or help text is not available

web.perserver.requests.cached.size.le10k
Full Help: Error: One-line or help text is not available

web.perserver.requests.cached.size.le30k
Full Help: Error: One-line or help text is not available

web.perserver.requests.cached.size.le100k
Full Help: Error: One-line or help text is not available

web.perserver.requests.cached.size.le300k
Full Help: Error: One-line or help text is not available

web.perserver.requests.cached.size.le1m
Full Help: Error: One-line or help text is not available

web.perserver.requests.cached.size.le3m
Full Help: Error: One-line or help text is not available

web.perserver.requests.cached.size.gt3m
Full Help: Error: One-line or help text is not available

web.perserver.requests.cached.size.unknown
Full Help: Error: One-line or help text is not available

web.perserver.requests.uncached.total
Full Help: Error: One-line or help text is not available

web.perserver.requests.uncached.size.zero
Full Help: Error: One-line or help text is not available

web.perserver.requests.uncached.size.le3k
Full Help: Error: One-line or help text is not available

web.perserver.requests.uncached.size.le10k
Full Help: Error: One-line or help text is not available

web.perserver.requests.uncached.size.le30k
Full Help: Error: One-line or help text is not available

web.perserver.requests.uncached.size.le100k
Full Help: Error: One-line or help text is not available

web.perserver.requests.uncached.size.le300k
Full Help: Error: One-line or help text is not available

web.perserver.requests.uncached.size.le1m
Full Help: Error: One-line or help text is not available

web.perserver.requests.uncached.size.le3m
Full Help: Error: One-line or help text is not available

web.perserver.requests.uncached.size.gt3m
Full Help: Error: One-line or help text is not available

web.perserver.requests.uncached.size.unknown
Full Help: Error: One-line or help text is not available

web.perserver.bytes.total
Full Help: Error: One-line or help text is not available

web.perserver.bytes.get
Full Help: Error: One-line or help text is not available

web.perserver.bytes.head
Full Help: Error: One-line or help text is not available

web.perserver.bytes.post
Full Help: Error: One-line or help text is not available

web.perserver.bytes.other
Full Help: Error: One-line or help text is not available

web.perserver.bytes.size.zero
Full Help: Error: One-line or help text is not available

web.perserver.bytes.size.le3k
Full Help: Error: One-line or help text is not available

web.perserver.bytes.size.le10k
Full Help: Error: One-line or help text is not available

web.perserver.bytes.size.le30k
Full Help: Error: One-line or help text is not available

web.perserver.bytes.size.le100k
Full Help: Error: One-line or help text is not available

web.perserver.bytes.size.le300k
Full Help: Error: One-line or help text is not available

web.perserver.bytes.size.le1m
Full Help: Error: One-line or help text is not available

web.perserver.bytes.size.le3m
Full Help: Error: One-line or help text is not available

web.perserver.bytes.size.gt3m
Full Help: Error: One-line or help text is not available

web.perserver.bytes.cached.total
Full Help: Error: One-line or help text is not available

web.perserver.bytes.cached.size.zero
Full Help: Error: One-line or help text is not available

web.perserver.bytes.cached.size.le3k
Full Help: Error: One-line or help text is not available

web.perserver.bytes.cached.size.le10k
Full Help: Error: One-line or help text is not available

web.perserver.bytes.cached.size.le30k
Full Help: Error: One-line or help text is not available

web.perserver.bytes.cached.size.le100k
Full Help: Error: One-line or help text is not available

web.perserver.bytes.cached.size.le300k
Full Help: Error: One-line or help text is not available

web.perserver.bytes.cached.size.le1m
Full Help: Error: One-line or help text is not available

web.perserver.bytes.cached.size.le3m
Full Help: Error: One-line or help text is not available

web.perserver.bytes.cached.size.gt3m
Full Help: Error: One-line or help text is not available

web.perserver.bytes.uncached.total
Full Help: Error: One-line or help text is not available

web.perserver.bytes.uncached.size.zero
Full Help: Error: One-line or help text is not available

web.perserver.bytes.uncached.size.le3k
Full Help: Error: One-line or help text is not available

web.perserver.bytes.uncached.size.le10k
Full Help: Error: One-line or help text is not available

web.perserver.bytes.uncached.size.le30k
Full Help: Error: One-line or help text is not available

web.perserver.bytes.uncached.size.le100k
Full Help: Error: One-line or help text is not available

web.perserver.bytes.uncached.size.le300k
Full Help: Error: One-line or help text is not available

web.perserver.bytes.uncached.size.le1m
Full Help: Error: One-line or help text is not available

web.perserver.bytes.uncached.size.le3m
Full Help: Error: One-line or help text is not available

web.perserver.bytes.uncached.size.gt3m
Full Help: Error: One-line or help text is not available
```

**Comment by kmcdonell** [comment] 2023-05-10 21:34
This issue is not understood, but it is not apparently reproducible.  The help text files for this PMDA are packaged and installed and appear to be available once the PMDA is in use by pmcd(1).
Closing the issue, please re-open if the problem is observed again.

**Closed by kmcdonell** 2023-05-10 21:34 UTC
