### ISSUE TITLE
performance regression: pmie retrying at 5s against older pmcds

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp#315] opened 2017-06-27 15:38 UTC
A pmie design decision is causing a great deal of work on hosts that run pmie itself and on targeted pmcd hosts, when the pmie configuration asks for metrics that the pmcd host does not include.  This can easily happen because - unlike pmlogconf - pmieconf is target-host-unaware.  New pmieconf default queries, like the kernel-entropy bits, will be naturally rebuked by older pmcds.  Then pmie backs down to a "retry fetching all the metrics every 5 seconds" (instead of the default 2/4 minute declared delta").  This causes very noticeable load on both pmie and the remote pmcd, in terms of accumulated CPU time.  It's plainly visible on strace too.

If this kind of frequent retrying is indeed a good idea, it should be limited to retrying the -failing- operations only (in this case, a pmLookupName), and not a complete fetch of every metric.

**Comment by kmcdonell** [comment] 2017-07-02 21:56
> -----Original Message-----
> From: Frank Ch. Eigler [mailto:notifications@github.com]
> Sent: Wednesday, June 28, 2017 1:39 AM
> To: performancecopilot/pcp <pcp@noreply.github.com>
> Cc: Subscribed <subscribed@noreply.github.com>
> Subject: [performancecopilot/pcp] performance regression: pmie retrying at 5s
> against older pmcds (#315)
> 
> A pmie design decision is causing a great deal of work on hosts that run pmie
> itself and on targeted pmcd hosts, when the pmie configuration asks for metrics
> that the pmcd host does not include. This can easily happen because - unlike
> pmlogconf - pmieconf is target-host-unaware. New pmieconf default queries, like
> the kernel-entropy bits, will be naturally rebuked by older pmcds. Then pmie
> backs down to a "retry fetching all the metrics every 5 seconds" (instead of
> the default 2/4 minute declared delta"). This causes very noticeable load on
> both pmie and the remote pmcd, in terms of accumulated CPU time. It's plainly
> visible on strace too.
> 
> If this kind of frequent retrying is indeed a good idea, it should be limited
> to retrying the -failing- operations only (in this case, a pmLookupName), and
> not a complete fetch of every metric.

I have a handle on this ... a fix is incoming once I've nutted out Seppo's logic and an appropriate QA test.

I am proposing that in cases were pmie cannot get the metadata for a metric or contact a host, any associated rule evaluations will use an exponential backoff delay of 5, 20, 80, 320, ... seconds, capped at 3600 seconds.

**Comment by fche** [comment] 2017-07-03 12:33
>  I am proposing that in cases were pmie cannot get the metadata for a metric or contact a host, any associated rule evaluations will use an exponential backoff delay 

It could be enough to arrangepmie to not fetch any unrelated metrics if a rule's metric metadata is incomplete.  Nor to fetch any other metrics of the same rule.  At that point, the exponential part of the backoff probably isn't necessary.  (I assume that someone would put a pmie[conf] rule in anticipating that the metric might appear at any moment, like from a dynamic PMNS PMDA.  For something like kernel.all.entropy.*, a pmlogconf-like one-time 'probe' would be more appropriate, but alas.)

**Comment by kmcdonell** [comment] 2017-07-04 00:14
It is a little tricky (no surprise).
We have to balance the following requirements:
1. a pmcd may be down for a short time (reboot, bring up, ...) or a long time (really down, dead, VM not running)
2. when a pmcd is up, a PMDA may be unavailable for a short time (being installed) or a long time (never going to be installed)
3. when a PMDA is available, a metric may be unavailable for a short time (not ready and related startups) or a long time (no support, not in PMNS for this version)
4. the presence of disjunction, existential quantification and sum_* predicates in the expression language mean that even if some leaf nodes are unavailable, the entire expression may still be able to be evaluated and so we may try a pmFetch (or two)

Point 4. means that with the current expression evaluation engine we don't have enough feedback to know if fetching some of the metrics is sufficient to evaluate the expression, so we must attempt to fetch values for all leaf nodes in the expression tree, and then let the expression evaluator decide what to do with the "missing" values.

The historical behaviour was that if the metric metadata was not available (independent of the cause being 1. or 2. or 3. above) we tried to evaluate the expression (which triggers an attempt to fetch the missing metadata) every 5secs.  This was biased in favour of short-term delays from 1. or 2. or 3. above.

What I'm trying to do is swing the balanace back a little towards less frequent attempts if it looks like the long-term delays are in effect.

I need to modify my suggested change that it will use exponential back off (probably x 2 rather than x 4, from a 5 sec base) and be capped at the expression's fetch (refresh) interval.

So this means in the case you originally reported we'd try at intervals of 5, 10, 20, 40, 80 and 120 (forever) if the associated delta was 2 minutes.

**Comment by kmcdonell** [comment] 2017-08-03 07:33
Fixed in [https://github.com/performancecopilot/pcp/commit/5e00ec96c3094ed10e747ba2d4d79a9e11a1fd4d]

**Closed by kmcdonell** 2017-08-03 07:33 UTC
