### ISSUE TITLE
compressed archive volumes hobble pmwebd graphite webapi (Bugzilla #1099)

### ISSUE THREAD

**Issue by pcpemail** [performancecopilot/pcp#188] opened 2016-10-26 02:37 UTC
On 2014-12-15 14:19:58 -0600, Frank Ch. Eigler wrote:

> When pmwebd scans an directory of archives that contain compressed
> volumes, libpcp causes each file to be decompressed, briefly analyzed,
> and then tossed away.  Even one round of bunzip2'ing a single file
> takes too long; but imagine what a directory full of them does.
> 
> It would be nice if we had some combination of:
> - a way of directly accessing compressed files in situ,
>   as in zlib or libbz2 ... except they are not normally seekable
> - use of a seekable compression tool/library like dictzip
>   (it's in the dictd package, dictd_data_read_ etc.,
>   licensed GPL1+, so usable)
>   
>   http://stackoverflow.com/questions/429987/compression-formats-with-good-support-for-random-access-within-archives/4010096
> - tweak libpcp so it does not decompress whole volume files
>   just to answer basic queries like PMNS enumeration, log start and 
>   _end_ times, which are generally in the .meta / .index.  (The
>   archive end is not so nigh -- maybe we need a pcp-archive format
>   tweak, or perhaps an fstat()-based heuristic?)
> - tweak libpcp so that decompressed files are kept in a cache
>   for a while, to avoid redecompression
> - a way of letting pmwebd open up numerous long-lived pmcontext's,
>   so any explicit decompression step would have to be paid-for only
>   once

On 2015-08-19 07:00:30 -0500, Frank Ch. Eigler wrote:

> Some mitigation in 3.10.5+
> 
> commit SHA: 738ccc07e942d295ec516814e7b52f9c910555d8
> Author: Frank Ch. Eigler fche@redhat.com
> Date:   Tue Apr 21 18:12:59 2015 -0400
> 
> ```
> PR1099 (compressed archive) mitigation in pmwebd: skip them in graphite mode
> ```

**Comment by willdarton** [comment] 2016-11-23 19:53
Is this likely to still be an issue in 3.11.3-4 ?  Seem to be noticing the same behavior with pmwebd not returning graphite info

**Comment by fche** [comment] 2016-11-23 21:35
This mitigation was removed in pcp 3.11.3.
<pre>
commit f1fdb217a59506ee1b16ed113727bee3fa170d68
Author: Nathan Scott <nathans@redhat.com>
Date:   Mon May 9 09:33:12 2016 +1000
</pre>

**Comment by natoscott** [comment] 2016-11-24 20:52
@willdarton the only work that has been done to address the root cause was

commit 12da325fa449ad775b892437e84b8db0ef60fbac
Author: Nathan Scott <nathans@redhat.com>
Date:   Fri Sep 4 17:07:10 2015 +1000

    libpcp: optimise archive decompression for common operations

(which will be in that version range you mention)

Have you confirmed the problem is definitely resolved using uncompressed archives?  There are lots of other workarounds - logging to faster storage, logging less (what are the sizes of your archives OOC?), and/or removing use of the -x option pmlogger_check in /etc/cron.d/pcp-pmlogger of course.

**Comment by willdarton** [comment] 2016-11-27 23:01
@natoscott I did in fact confirm that uncompressing the files resolved the issue with being able to scan the files via graphite or grafana.  I have opened a case with Red Hat.  As far as faster storage, this is a VMware virtual machine running on ESX Hosts in a pretty recent version of VMware backed by enterprise class IBM storage.  Obviously its likely not SSD but tbh I don't know that that would be appropriate
We have disabled  -x and -X in pmlogger_check which has the benefit of causing pmwebd to function, but the disadvantage of increased storage by many factors, and removing the benefit of the compression in pmlogger.

the logfiles compressed are around 494016, there are about 144 hosts currently being logged with about 30 days worth of data thus far.

**Comment by natoscott** [comment] 2016-11-27 23:57
@willdarton perfect, thanks Will!  Those final data points in particular are very handy, though do you have an average uncompressed size?  Yes, its certainly an area we need to improve (rather than attempt to hide) - good to have that confirmed - and thanks for opening that case, I'll follow up on that too.

BTW, if you know what metrics you will need, a short-term workaround you could use is to pmlogextract(1) a subset of the metrics into a set of smaller archives and make only those accessible via pmwebd(1).  But, that's not a long-term solution - we'll be working towards something seamless in core PCP eventually.

cheers.

**Comment by goodwinos** [comment] 2016-11-28 01:28
I will open a RH BZ for Red Hat support case 01745906.
Apparently the xz compressed format already being used for PCP archive compression has an API called liblzma that supports block-level random access to xz files. Not sure what block sizes are supported,  but this should in principle provide what's needed for libpcp to read compressed archives insitu, without having to decompress them to temp space. See below /usr/src/debug/xz-5.2.2/src/liblzma/api in the xz-debuginfo package (or look in the xz source itself).

**Comment by natoscott** [comment] 2016-11-28 01:59
@goodwinos thanks Mark.  FWIW, we have https://bugzilla.redhat.com/show_bug.cgi?id=1293471 for Fedora too.

**Comment by natoscott** [comment] 2020-02-26 01:08
pmwebd has been retired since PCP v5 - its replacement pmproxy provides a high-speed interface to Redis, avoiding the problem of decompressing archives for interactive applications.

**Closed by natoscott** 2020-02-26 01:08 UTC
