### ISSUE TITLE
Metrics of pcp-pmda-sendmail are missing help texts.

### ISSUE THREAD

**Issue by kurik** [performancecopilot/pcp#1276] opened 2021-05-10 16:31 UTC
Metrics of pcp-pmda-sendmail are missing help texts.

The following metrics of pcp-pmda-sendmail are missing online help texts.
This is output of ```pminfo -t``` filtered to metrics without a help text:
```
sendmail.start_date One-line Help: Error: One-line or help text is not available
sendmail.permailer.msgs_from One-line Help: Error: One-line or help text is not available
sendmail.permailer.bytes_from One-line Help: Error: One-line or help text is not available
sendmail.permailer.msgs_to One-line Help: Error: One-line or help text is not available
sendmail.permailer.bytes_to One-line Help: Error: One-line or help text is not available
sendmail.total.msgs_from One-line Help: Error: One-line or help text is not available
sendmail.total.bytes_from One-line Help: Error: One-line or help text is not available
sendmail.total.msgs_to One-line Help: Error: One-line or help text is not available
sendmail.total.bytes_to One-line Help: Error: One-line or help text is not available
```

The following metrics of pcp-pmda-sendmail are missing full help texts.
This is output of ```pminfo -T``` filtered to metrics without a help text:
```

sendmail.start_date
Full Help: Error: One-line or help text is not available

sendmail.permailer.msgs_from
Full Help: Error: One-line or help text is not available

sendmail.permailer.bytes_from
Full Help: Error: One-line or help text is not available

sendmail.permailer.msgs_to
Full Help: Error: One-line or help text is not available

sendmail.permailer.bytes_to
Full Help: Error: One-line or help text is not available

sendmail.total.msgs_from
Full Help: Error: One-line or help text is not available

sendmail.total.bytes_from
Full Help: Error: One-line or help text is not available

sendmail.total.msgs_to
Full Help: Error: One-line or help text is not available

sendmail.total.bytes_to
Full Help: Error: One-line or help text is not available
```

**Comment by kmcdonell** [comment] 2023-05-10 21:38
This issue is not understood, but it is not apparently reproducible.  The help text files for this PMDA are packaged and installed and appear to be available once the PMDA is in use by pmcd(1).
Closing the issue, please re-open if the problem is observed again.

**Closed by kmcdonell** 2023-05-10 21:38 UTC
