### ISSUE TITLE
Metrics of pcp-pmda-cifs are missing help texts.

### ISSUE THREAD

**Issue by kurik** [performancecopilot/pcp#1259] opened 2021-05-10 15:08 UTC
Metrics of pcp-pmda-cifs are missing help texts.

The following metrics of pcp-pmda-cifs are missing online help texts.
This is output of ```pminfo -t``` filtered to metrics without a help text:
```
cifs.session One-line Help: Error: One-line or help text is not available
cifs.shares One-line Help: Error: One-line or help text is not available
cifs.buffer One-line Help: Error: One-line or help text is not available
cifs.pool_size One-line Help: Error: One-line or help text is not available
cifs.small_buffer One-line Help: Error: One-line or help text is not available
cifs.small_pool_size One-line Help: Error: One-line or help text is not available
cifs.mid_operations One-line Help: Error: One-line or help text is not available
cifs.total_operations One-line Help: Error: One-line or help text is not available
cifs.total_reconnects One-line Help: Error: One-line or help text is not available
cifs.vfs_operations One-line Help: Error: One-line or help text is not available
cifs.vfs_operations_max One-line Help: Error: One-line or help text is not available
cifs.version One-line Help: Error: One-line or help text is not available
cifs.fs.connected One-line Help: Error: One-line or help text is not available
cifs.fs.smbs One-line Help: Error: One-line or help text is not available
cifs.fs.oplock_breaks One-line Help: Error: One-line or help text is not available
cifs.fs.read One-line Help: Error: One-line or help text is not available
cifs.fs.read_bytes One-line Help: Error: One-line or help text is not available
cifs.fs.write One-line Help: Error: One-line or help text is not available
cifs.fs.write_bytes One-line Help: Error: One-line or help text is not available
cifs.fs.flushes One-line Help: Error: One-line or help text is not available
cifs.fs.locks One-line Help: Error: One-line or help text is not available
cifs.fs.hard_links One-line Help: Error: One-line or help text is not available
cifs.fs.sym_links One-line Help: Error: One-line or help text is not available
cifs.fs.read_fails One-line Help: Error: One-line or help text is not available
cifs.fs.write_fails One-line Help: Error: One-line or help text is not available
cifs.fs.flushes_fails One-line Help: Error: One-line or help text is not available
cifs.fs.locks_fails One-line Help: Error: One-line or help text is not available
cifs.fs.negotiates One-line Help: Error: One-line or help text is not available
cifs.fs.negotiates_fails One-line Help: Error: One-line or help text is not available
cifs.fs.sessionsetups One-line Help: Error: One-line or help text is not available
cifs.fs.sessionsetups_fails One-line Help: Error: One-line or help text is not available
cifs.fs.logoffs One-line Help: Error: One-line or help text is not available
cifs.fs.logoffs_fails One-line Help: Error: One-line or help text is not available
cifs.fs.treecons One-line Help: Error: One-line or help text is not available
cifs.fs.treecons_fails One-line Help: Error: One-line or help text is not available
cifs.fs.treediscons One-line Help: Error: One-line or help text is not available
cifs.fs.treediscons_fails One-line Help: Error: One-line or help text is not available
cifs.fs.creates One-line Help: Error: One-line or help text is not available
cifs.fs.creates_fails One-line Help: Error: One-line or help text is not available
cifs.fs.IOCTLs One-line Help: Error: One-line or help text is not available
cifs.fs.IOCTLs_fails One-line Help: Error: One-line or help text is not available
cifs.fs.cancels One-line Help: Error: One-line or help text is not available
cifs.fs.cancels_fails One-line Help: Error: One-line or help text is not available
cifs.fs.echos One-line Help: Error: One-line or help text is not available
cifs.fs.echos_fails One-line Help: Error: One-line or help text is not available
cifs.fs.querydirs One-line Help: Error: One-line or help text is not available
cifs.fs.querydirs_fails One-line Help: Error: One-line or help text is not available
cifs.fs.changenotifies One-line Help: Error: One-line or help text is not available
cifs.fs.changenotifies_fails One-line Help: Error: One-line or help text is not available
cifs.fs.queryinfos One-line Help: Error: One-line or help text is not available
cifs.fs.queryinfos_fails One-line Help: Error: One-line or help text is not available
cifs.fs.setinfos One-line Help: Error: One-line or help text is not available
cifs.fs.setinfos_fails One-line Help: Error: One-line or help text is not available
cifs.fs.oplock_breaks_fails One-line Help: Error: One-line or help text is not available
cifs.ops.open One-line Help: Error: One-line or help text is not available
cifs.ops.close One-line Help: Error: One-line or help text is not available
cifs.ops.close_fails One-line Help: Error: One-line or help text is not available
cifs.ops.delete One-line Help: Error: One-line or help text is not available
cifs.ops.posix_open One-line Help: Error: One-line or help text is not available
cifs.ops.posix_mkdir One-line Help: Error: One-line or help text is not available
cifs.ops.mkdir One-line Help: Error: One-line or help text is not available
cifs.ops.rmdir One-line Help: Error: One-line or help text is not available
cifs.ops.rename One-line Help: Error: One-line or help text is not available
cifs.ops.t2_rename One-line Help: Error: One-line or help text is not available
cifs.ops.find_first One-line Help: Error: One-line or help text is not available
cifs.ops.find_next One-line Help: Error: One-line or help text is not available
cifs.ops.find_close One-line Help: Error: One-line or help text is not available
```

The following metrics of pcp-pmda-cifs are missing full help texts.
This is output of ```pminfo -T``` filtered to metrics without a help text:
```

cifs.session
Full Help: Error: One-line or help text is not available

cifs.shares
Full Help: Error: One-line or help text is not available

cifs.buffer
Full Help: Error: One-line or help text is not available

cifs.pool_size
Full Help: Error: One-line or help text is not available

cifs.small_buffer
Full Help: Error: One-line or help text is not available

cifs.small_pool_size
Full Help: Error: One-line or help text is not available

cifs.mid_operations
Full Help: Error: One-line or help text is not available

cifs.total_operations
Full Help: Error: One-line or help text is not available

cifs.total_reconnects
Full Help: Error: One-line or help text is not available

cifs.vfs_operations
Full Help: Error: One-line or help text is not available

cifs.vfs_operations_max
Full Help: Error: One-line or help text is not available

cifs.version
Full Help: Error: One-line or help text is not available

cifs.fs.connected
Full Help: Error: One-line or help text is not available

cifs.fs.smbs
Full Help: Error: One-line or help text is not available

cifs.fs.oplock_breaks
Full Help: Error: One-line or help text is not available

cifs.fs.read
Full Help: Error: One-line or help text is not available

cifs.fs.read_bytes
Full Help: Error: One-line or help text is not available

cifs.fs.write
Full Help: Error: One-line or help text is not available

cifs.fs.write_bytes
Full Help: Error: One-line or help text is not available

cifs.fs.flushes
Full Help: Error: One-line or help text is not available

cifs.fs.locks
Full Help: Error: One-line or help text is not available

cifs.fs.hard_links
Full Help: Error: One-line or help text is not available

cifs.fs.sym_links
Full Help: Error: One-line or help text is not available

cifs.fs.read_fails
Full Help: Error: One-line or help text is not available

cifs.fs.write_fails
Full Help: Error: One-line or help text is not available

cifs.fs.flushes_fails
Full Help: Error: One-line or help text is not available

cifs.fs.locks_fails
Full Help: Error: One-line or help text is not available

cifs.fs.negotiates
Full Help: Error: One-line or help text is not available

cifs.fs.negotiates_fails
Full Help: Error: One-line or help text is not available

cifs.fs.sessionsetups
Full Help: Error: One-line or help text is not available

cifs.fs.sessionsetups_fails
Full Help: Error: One-line or help text is not available

cifs.fs.logoffs
Full Help: Error: One-line or help text is not available

cifs.fs.logoffs_fails
Full Help: Error: One-line or help text is not available

cifs.fs.treecons
Full Help: Error: One-line or help text is not available

cifs.fs.treecons_fails
Full Help: Error: One-line or help text is not available

cifs.fs.treediscons
Full Help: Error: One-line or help text is not available

cifs.fs.treediscons_fails
Full Help: Error: One-line or help text is not available

cifs.fs.creates
Full Help: Error: One-line or help text is not available

cifs.fs.creates_fails
Full Help: Error: One-line or help text is not available

cifs.fs.IOCTLs
Full Help: Error: One-line or help text is not available

cifs.fs.IOCTLs_fails
Full Help: Error: One-line or help text is not available

cifs.fs.cancels
Full Help: Error: One-line or help text is not available

cifs.fs.cancels_fails
Full Help: Error: One-line or help text is not available

cifs.fs.echos
Full Help: Error: One-line or help text is not available

cifs.fs.echos_fails
Full Help: Error: One-line or help text is not available

cifs.fs.querydirs
Full Help: Error: One-line or help text is not available

cifs.fs.querydirs_fails
Full Help: Error: One-line or help text is not available

cifs.fs.changenotifies
Full Help: Error: One-line or help text is not available

cifs.fs.changenotifies_fails
Full Help: Error: One-line or help text is not available

cifs.fs.queryinfos
Full Help: Error: One-line or help text is not available

cifs.fs.queryinfos_fails
Full Help: Error: One-line or help text is not available

cifs.fs.setinfos
Full Help: Error: One-line or help text is not available

cifs.fs.setinfos_fails
Full Help: Error: One-line or help text is not available

cifs.fs.oplock_breaks_fails
Full Help: Error: One-line or help text is not available

cifs.ops.open
Full Help: Error: One-line or help text is not available

cifs.ops.close
Full Help: Error: One-line or help text is not available

cifs.ops.close_fails
Full Help: Error: One-line or help text is not available

cifs.ops.delete
Full Help: Error: One-line or help text is not available

cifs.ops.posix_open
Full Help: Error: One-line or help text is not available

cifs.ops.posix_mkdir
Full Help: Error: One-line or help text is not available

cifs.ops.mkdir
Full Help: Error: One-line or help text is not available

cifs.ops.rmdir
Full Help: Error: One-line or help text is not available

cifs.ops.rename
Full Help: Error: One-line or help text is not available

cifs.ops.t2_rename
Full Help: Error: One-line or help text is not available

cifs.ops.find_first
Full Help: Error: One-line or help text is not available

cifs.ops.find_next
Full Help: Error: One-line or help text is not available

cifs.ops.find_close
Full Help: Error: One-line or help text is not available
```

**Comment by kmcdonell** [comment] 2023-05-10 21:46
This issue is not understood, but it is not apparently reproducible.  The help text files for this PMDA are packaged and installed and appear to be available once the PMDA is in use by pmcd(1).
Closing the issue, please re-open if the problem is observed again.

**Closed by kmcdonell** 2023-05-10 21:46 UTC
