### ISSUE TITLE
Metrics of pcp-pmda-infiniband are missing help texts.

### ISSUE THREAD

**Issue by kurik** [performancecopilot/pcp#1264] opened 2021-05-10 16:23 UTC
Metrics of pcp-pmda-infiniband are missing help texts.

The following metrics of pcp-pmda-infiniband are missing online help texts.
This is output of ```pminfo -t``` filtered to metrics without a help text:
```
infiniband.hca.type One-line Help: Error: One-line or help text is not available
infiniband.hca.ca_type One-line Help: Error: One-line or help text is not available
infiniband.hca.numports One-line Help: Error: One-line or help text is not available
infiniband.hca.fw_ver One-line Help: Error: One-line or help text is not available
infiniband.hca.hw_ver One-line Help: Error: One-line or help text is not available
infiniband.hca.node_guid One-line Help: Error: One-line or help text is not available
infiniband.hca.system_guid One-line Help: Error: One-line or help text is not available
infiniband.port.guid One-line Help: Error: One-line or help text is not available
infiniband.port.gid_prefix One-line Help: Error: One-line or help text is not available
infiniband.port.lid One-line Help: Error: One-line or help text is not available
infiniband.port.state One-line Help: Error: One-line or help text is not available
infiniband.port.phystate One-line Help: Error: One-line or help text is not available
infiniband.port.rate One-line Help: Error: One-line or help text is not available
infiniband.port.capabilities One-line Help: Error: One-line or help text is not available
infiniband.port.linkspeed One-line Help: Error: One-line or help text is not available
infiniband.port.linkwidth One-line Help: Error: One-line or help text is not available
infiniband.port.in.bytes One-line Help: Error: One-line or help text is not available
infiniband.port.in.packets One-line Help: Error: One-line or help text is not available
infiniband.port.in.errors.drop One-line Help: Error: One-line or help text is not available
infiniband.port.in.errors.filter One-line Help: Error: One-line or help text is not available
infiniband.port.in.errors.local One-line Help: Error: One-line or help text is not available
infiniband.port.in.errors.remote One-line Help: Error: One-line or help text is not available
infiniband.port.out.bytes One-line Help: Error: One-line or help text is not available
infiniband.port.out.packets One-line Help: Error: One-line or help text is not available
infiniband.port.out.errors.drop One-line Help: Error: One-line or help text is not available
infiniband.port.out.errors.filter One-line Help: Error: One-line or help text is not available
infiniband.port.total.bytes One-line Help: Error: One-line or help text is not available
infiniband.port.total.packets One-line Help: Error: One-line or help text is not available
infiniband.port.total.errors.drop One-line Help: Error: One-line or help text is not available
infiniband.port.total.errors.filter One-line Help: Error: One-line or help text is not available
infiniband.port.total.errors.link One-line Help: Error: One-line or help text is not available
infiniband.port.total.errors.recover One-line Help: Error: One-line or help text is not available
infiniband.port.total.errors.integrity One-line Help: Error: One-line or help text is not available
infiniband.port.total.errors.vl15 One-line Help: Error: One-line or help text is not available
infiniband.port.total.errors.overrun One-line Help: Error: One-line or help text is not available
infiniband.port.total.errors.symbol One-line Help: Error: One-line or help text is not available
infiniband.port.switch.in.bytes One-line Help: Error: One-line or help text is not available
infiniband.port.switch.in.packets One-line Help: Error: One-line or help text is not available
infiniband.port.switch.out.bytes One-line Help: Error: One-line or help text is not available
infiniband.port.switch.out.packets One-line Help: Error: One-line or help text is not available
infiniband.port.switch.total.bytes One-line Help: Error: One-line or help text is not available
infiniband.port.switch.total.packets One-line Help: Error: One-line or help text is not available
infiniband.control.query_timeout One-line Help: Error: One-line or help text is not available
infiniband.control.hiwat One-line Help: Error: One-line or help text is not available
```

The following metrics of pcp-pmda-infiniband are missing full help texts.
This is output of ```pminfo -T``` filtered to metrics without a help text:
```

infiniband.hca.type
Full Help: Error: One-line or help text is not available

infiniband.hca.ca_type
Full Help: Error: One-line or help text is not available

infiniband.hca.numports
Full Help: Error: One-line or help text is not available

infiniband.hca.fw_ver
Full Help: Error: One-line or help text is not available

infiniband.hca.hw_ver
Full Help: Error: One-line or help text is not available

infiniband.hca.node_guid
Full Help: Error: One-line or help text is not available

infiniband.hca.system_guid
Full Help: Error: One-line or help text is not available

infiniband.port.guid
Full Help: Error: One-line or help text is not available

infiniband.port.gid_prefix
Full Help: Error: One-line or help text is not available

infiniband.port.lid
Full Help: Error: One-line or help text is not available

infiniband.port.state
Full Help: Error: One-line or help text is not available

infiniband.port.phystate
Full Help: Error: One-line or help text is not available

infiniband.port.rate
Full Help: Error: One-line or help text is not available

infiniband.port.capabilities
Full Help: Error: One-line or help text is not available

infiniband.port.linkspeed
Full Help: Error: One-line or help text is not available

infiniband.port.linkwidth
Full Help: Error: One-line or help text is not available

infiniband.port.in.bytes
Full Help: Error: One-line or help text is not available

infiniband.port.in.packets
Full Help: Error: One-line or help text is not available

infiniband.port.in.errors.drop
Full Help: Error: One-line or help text is not available

infiniband.port.in.errors.filter
Full Help: Error: One-line or help text is not available

infiniband.port.in.errors.local
Full Help: Error: One-line or help text is not available

infiniband.port.in.errors.remote
Full Help: Error: One-line or help text is not available

infiniband.port.out.bytes
Full Help: Error: One-line or help text is not available

infiniband.port.out.packets
Full Help: Error: One-line or help text is not available

infiniband.port.out.errors.drop
Full Help: Error: One-line or help text is not available

infiniband.port.out.errors.filter
Full Help: Error: One-line or help text is not available

infiniband.port.total.bytes
Full Help: Error: One-line or help text is not available

infiniband.port.total.packets
Full Help: Error: One-line or help text is not available

infiniband.port.total.errors.drop
Full Help: Error: One-line or help text is not available

infiniband.port.total.errors.filter
Full Help: Error: One-line or help text is not available

infiniband.port.total.errors.link
Full Help: Error: One-line or help text is not available

infiniband.port.total.errors.recover
Full Help: Error: One-line or help text is not available

infiniband.port.total.errors.integrity
Full Help: Error: One-line or help text is not available

infiniband.port.total.errors.vl15
Full Help: Error: One-line or help text is not available

infiniband.port.total.errors.overrun
Full Help: Error: One-line or help text is not available

infiniband.port.total.errors.symbol
Full Help: Error: One-line or help text is not available

infiniband.port.switch.in.bytes
Full Help: Error: One-line or help text is not available

infiniband.port.switch.in.packets
Full Help: Error: One-line or help text is not available

infiniband.port.switch.out.bytes
Full Help: Error: One-line or help text is not available

infiniband.port.switch.out.packets
Full Help: Error: One-line or help text is not available

infiniband.port.switch.total.bytes
Full Help: Error: One-line or help text is not available

infiniband.port.switch.total.packets
Full Help: Error: One-line or help text is not available

infiniband.control.query_timeout
Full Help: Error: One-line or help text is not available

infiniband.control.hiwat
Full Help: Error: One-line or help text is not available
```

**Comment by kmcdonell** [comment] 2023-05-10 21:49
This issue is not understood, but it is not apparently reproducible.  The help text files for this PMDA are packaged and installed and appear to be available once the PMDA is in use by pmcd(1).
Closing the issue, please re-open if the problem is observed again.

**Closed by kmcdonell** 2023-05-10 21:49 UTC
