### ISSUE TITLE
Metrics of pcp-pmda-hacluster are missing help texts.

### ISSUE THREAD

**Issue by kurik** [performancecopilot/pcp#1263] opened 2021-05-10 15:12 UTC
Metrics of pcp-pmda-hacluster are missing help texts.

The following metrics of pcp-pmda-hacluster are missing online help texts.
This is output of ```pminfo -t``` filtered to metrics without a help text:
```
ha_cluster.pacemaker.config_last_change One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.fail_count One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.migration_threshold One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.node_attributes One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.stonith_enabled One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.location_constraints.node One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.location_constraints.resource One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.location_constraints.role One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.location_constraints.score One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.nodes.type One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.nodes.status.online One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.nodes.status.standby One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.nodes.status.standby_on_fail One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.nodes.status.maintenance One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.nodes.status.pending One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.nodes.status.unclean One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.nodes.status.shutdown One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.nodes.status.expected_up One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.nodes.status.dc One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.resources.agent One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.resources.clone One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.resources.group One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.resources.managed One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.resources.role One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.resources.status.active One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.resources.status.orphaned One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.resources.status.blocked One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.resources.status.failed One-line Help: Error: One-line or help text is not available
ha_cluster.pacemaker.resources.status.failure_ignored One-line Help: Error: One-line or help text is not available
ha_cluster.corosync.quorate One-line Help: Error: One-line or help text is not available
ha_cluster.corosync.ring_errors One-line Help: Error: One-line or help text is not available
ha_cluster.corosync.member_votes.votes One-line Help: Error: One-line or help text is not available
ha_cluster.corosync.member_votes.local One-line Help: Error: One-line or help text is not available
ha_cluster.corosync.member_votes.node_id One-line Help: Error: One-line or help text is not available
ha_cluster.corosync.quorum_votes.expected_votes One-line Help: Error: One-line or help text is not available
ha_cluster.corosync.quorum_votes.highest_expected One-line Help: Error: One-line or help text is not available
ha_cluster.corosync.quorum_votes.total_votes One-line Help: Error: One-line or help text is not available
ha_cluster.corosync.quorum_votes.quorum One-line Help: Error: One-line or help text is not available
ha_cluster.corosync.rings.status One-line Help: Error: One-line or help text is not available
ha_cluster.corosync.rings.address One-line Help: Error: One-line or help text is not available
ha_cluster.corosync.rings.node_id One-line Help: Error: One-line or help text is not available
ha_cluster.corosync.rings.number One-line Help: Error: One-line or help text is not available
ha_cluster.corosync.rings.ring_id One-line Help: Error: One-line or help text is not available
ha_cluster.sbd.devices.path One-line Help: Error: One-line or help text is not available
ha_cluster.sbd.devices.status One-line Help: Error: One-line or help text is not available
ha_cluster.sbd.timeouts.mgswait One-line Help: Error: One-line or help text is not available
ha_cluster.sbd.timeouts.allocate One-line Help: Error: One-line or help text is not available
ha_cluster.sbd.timeouts.loop One-line Help: Error: One-line or help text is not available
ha_cluster.sbd.timeouts.watchdog One-line Help: Error: One-line or help text is not available
ha_cluster.drbd.written One-line Help: Error: One-line or help text is not available
ha_cluster.drbd.read One-line Help: Error: One-line or help text is not available
ha_cluster.drbd.al_writes One-line Help: Error: One-line or help text is not available
ha_cluster.drbd.bm_writes One-line Help: Error: One-line or help text is not available
ha_cluster.drbd.upper_pending One-line Help: Error: One-line or help text is not available
ha_cluster.drbd.lower_pending One-line Help: Error: One-line or help text is not available
ha_cluster.drbd.quorum One-line Help: Error: One-line or help text is not available
ha_cluster.drbd.connections_sync One-line Help: Error: One-line or help text is not available
ha_cluster.drbd.connections_received One-line Help: Error: One-line or help text is not available
ha_cluster.drbd.connections_sent One-line Help: Error: One-line or help text is not available
ha_cluster.drbd.connections_pending One-line Help: Error: One-line or help text is not available
ha_cluster.drbd.connections_unacked One-line Help: Error: One-line or help text is not available
ha_cluster.drbd.split_brain One-line Help: Error: One-line or help text is not available
ha_cluster.drbd.resources.resource One-line Help: Error: One-line or help text is not available
ha_cluster.drbd.resources.role One-line Help: Error: One-line or help text is not available
ha_cluster.drbd.resources.volume One-line Help: Error: One-line or help text is not available
ha_cluster.drbd.resources.disk_state One-line Help: Error: One-line or help text is not available
ha_cluster.drbd.connections.resource One-line Help: Error: One-line or help text is not available
ha_cluster.drbd.connections.peer_node_id One-line Help: Error: One-line or help text is not available
ha_cluster.drbd.connections.peer_role One-line Help: Error: One-line or help text is not available
ha_cluster.drbd.connections.volume One-line Help: Error: One-line or help text is not available
ha_cluster.drbd.connections.peer_disk_state One-line Help: Error: One-line or help text is not available
```

The following metrics of pcp-pmda-hacluster are missing full help texts.
This is output of ```pminfo -T``` filtered to metrics without a help text:
```

ha_cluster.pacemaker.config_last_change
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.fail_count
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.migration_threshold
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.node_attributes
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.stonith_enabled
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.location_constraints.node
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.location_constraints.resource
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.location_constraints.role
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.location_constraints.score
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.nodes.type
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.nodes.status.online
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.nodes.status.standby
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.nodes.status.standby_on_fail
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.nodes.status.maintenance
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.nodes.status.pending
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.nodes.status.unclean
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.nodes.status.shutdown
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.nodes.status.expected_up
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.nodes.status.dc
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.resources.agent
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.resources.clone
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.resources.group
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.resources.managed
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.resources.role
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.resources.status.active
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.resources.status.orphaned
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.resources.status.blocked
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.resources.status.failed
Full Help: Error: One-line or help text is not available

ha_cluster.pacemaker.resources.status.failure_ignored
Full Help: Error: One-line or help text is not available

ha_cluster.corosync.quorate
Full Help: Error: One-line or help text is not available

ha_cluster.corosync.ring_errors
Full Help: Error: One-line or help text is not available

ha_cluster.corosync.member_votes.votes
Full Help: Error: One-line or help text is not available

ha_cluster.corosync.member_votes.local
Full Help: Error: One-line or help text is not available

ha_cluster.corosync.member_votes.node_id
Full Help: Error: One-line or help text is not available

ha_cluster.corosync.quorum_votes.expected_votes
Full Help: Error: One-line or help text is not available

ha_cluster.corosync.quorum_votes.highest_expected
Full Help: Error: One-line or help text is not available

ha_cluster.corosync.quorum_votes.total_votes
Full Help: Error: One-line or help text is not available

ha_cluster.corosync.quorum_votes.quorum
Full Help: Error: One-line or help text is not available

ha_cluster.corosync.rings.status
Full Help: Error: One-line or help text is not available

ha_cluster.corosync.rings.address
Full Help: Error: One-line or help text is not available

ha_cluster.corosync.rings.node_id
Full Help: Error: One-line or help text is not available

ha_cluster.corosync.rings.number
Full Help: Error: One-line or help text is not available

ha_cluster.corosync.rings.ring_id
Full Help: Error: One-line or help text is not available

ha_cluster.sbd.devices.path
Full Help: Error: One-line or help text is not available

ha_cluster.sbd.devices.status
Full Help: Error: One-line or help text is not available

ha_cluster.sbd.timeouts.mgswait
Full Help: Error: One-line or help text is not available

ha_cluster.sbd.timeouts.allocate
Full Help: Error: One-line or help text is not available

ha_cluster.sbd.timeouts.loop
Full Help: Error: One-line or help text is not available

ha_cluster.sbd.timeouts.watchdog
Full Help: Error: One-line or help text is not available

ha_cluster.drbd.written
Full Help: Error: One-line or help text is not available

ha_cluster.drbd.read
Full Help: Error: One-line or help text is not available

ha_cluster.drbd.al_writes
Full Help: Error: One-line or help text is not available

ha_cluster.drbd.bm_writes
Full Help: Error: One-line or help text is not available

ha_cluster.drbd.upper_pending
Full Help: Error: One-line or help text is not available

ha_cluster.drbd.lower_pending
Full Help: Error: One-line or help text is not available

ha_cluster.drbd.quorum
Full Help: Error: One-line or help text is not available

ha_cluster.drbd.connections_sync
Full Help: Error: One-line or help text is not available

ha_cluster.drbd.connections_received
Full Help: Error: One-line or help text is not available

ha_cluster.drbd.connections_sent
Full Help: Error: One-line or help text is not available

ha_cluster.drbd.connections_pending
Full Help: Error: One-line or help text is not available

ha_cluster.drbd.connections_unacked
Full Help: Error: One-line or help text is not available

ha_cluster.drbd.split_brain
Full Help: Error: One-line or help text is not available

ha_cluster.drbd.resources.resource
Full Help: Error: One-line or help text is not available

ha_cluster.drbd.resources.role
Full Help: Error: One-line or help text is not available

ha_cluster.drbd.resources.volume
Full Help: Error: One-line or help text is not available

ha_cluster.drbd.resources.disk_state
Full Help: Error: One-line or help text is not available

ha_cluster.drbd.connections.resource
Full Help: Error: One-line or help text is not available

ha_cluster.drbd.connections.peer_node_id
Full Help: Error: One-line or help text is not available

ha_cluster.drbd.connections.peer_role
Full Help: Error: One-line or help text is not available

ha_cluster.drbd.connections.volume
Full Help: Error: One-line or help text is not available

ha_cluster.drbd.connections.peer_disk_state
Full Help: Error: One-line or help text is not available
```

**Comment by kmcdonell** [comment] 2023-05-10 21:45
This issue is not understood, but it is not apparently reproducible.  The help text files for this PMDA are packaged and installed and appear to be available once the PMDA is in use by pmcd(1).
Closing the issue, please re-open if the problem is observed again.

**Closed by kmcdonell** 2023-05-10 21:45 UTC
