### ISSUE TITLE
Two config files created for pmie

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#1149] opened 2020-11-19 10:06 UTC
With current git code built on RHEL 8 and freshly installed PCP (including the pcp-zeroconf package) I see two config files being created for pmie:

```
root@rhel-8-server:~# ls -l /etc/pcp/pmie/config.default /var/lib/pcp/config/pmie/config.default 
-rw-r--r--. 1 root root 5.4K 2020-11-19 11:59 /etc/pcp/pmie/config.default
-rw-r--r--. 1 pcp  pcp  5.1K 2020-11-19 11:59 /var/lib/pcp/config/pmie/config.default
root@rhel-8-server:~# 
```

Since `/etc/pcp/pmie/control` only uses the basename of the config file, not the full path, it was not obvious which one was in use but after some experiment it seems to be the one under /var.

Given that all pmieconf files are under /var as symlinks to /etc and class/control being under /etc, I wonder should there be a symlink for config.default from /var to /etc (or vice versa) as well so that all the pmie related files would be found under /etc?

Thanks.

**Comment by goodwinos** [comment] 2020-11-20 06:36
Both /etc/pcp/pmie/config.default and /var/lib/pcp/config/pmie/config.default are generated files (not owned by any package). Remove both and then restart the pmie service causes pmie_check to call pmieconf to generate a new  /var/lib/pcp/config/pmie/config.default and that is the one used by the pmie service. After that, /etc/pcp/pmie/config.default no longer exists (and I'm not even sure how it got created in the first place). This is consistent with pmlogconf and the pmlogger service using /var/lib/pcp/config/pmlogger as the dirname for looking for config files named in it's control file(s).

So it would seem the bug here is to figure out what created /etc/pcp/pmie/config.default. Marko,which spec did you build from? Makepkgs with pcp.spec.in, or rpmbuild with redhat.spec?

In addition, if pmieconf / pmie_check and pmlogconf / pmlogger_check scripts want to write to /etc, they're going to need SELinux rules to allow that.

**Comment by myllynen** [comment] 2020-11-20 10:03
I have a clean git checkout and did this on the RHEL 8 test VM:

`cd /root/pcp.git/ ; git fetch --all ; git pull ; ./Makepkgs ;`

Then after creating the RPM repo reinstalled with:

```
#!/bin/sh
systemctl stop pmcd pmie pmlogger pmproxy redis grafana-server
dnf remove --noautoremove -y pcp\*
rm -rf /etc/pcp* /var/lib/pcp/ /var/log/pcp/ /var/lib/dnf/yumdb/p /var/cache/dnf/pcp*
rm -rf /usr/libexec/pcp /tmp/pcp.* /var/tmp/pcp.*
rm -rf /usr/share/pcp /usr/share/pcp-gui
systemctl daemon-reload
dnf --enablerepo=pcp install -y \
  pcp \
  pcp-devel \
  pcp-doc \
...
```

Thanks.

**Comment by goodwinos** [comment] 2020-11-25 00:04
The culprit is this line in the %post scriptlet for pcp-zeroconf in the RPM spec:
`pmieconf -c enable dmthin`
The default config file used by pmieconf is $PCP_SYSCONF_DIR/pmie/config.default. However pmie_check runs pmieconf with  the -f option and writes $PCP_VAR_DIR/config/pmie/config.default (which is consistent with pmlogconf and pmlogger_check), and the pmie service uses config.default from /var, not /etc.

So basically installing pcp-zeroconf results in the extra config.default in /etc, but we can't just remove that file and we can't recklessly change the default. So the fix is messy. Discussing with Nathan, we think the best course would be to document that the default config file is $PCP_VAR_DIR/config/pmie/config.default when pmieconf is run with the -c option. If -c is not given, then the default remains $PCP_SYSCONF_DIR/pmie/config.default. In all cases, pmieconf -f overrides the defaults.

**Comment by myllynen** [comment] 2020-11-25 19:06
Without not understanding all the nuances involved in this, how about also creating a sym link /etc/pcp/pmie/config.default -> /var/lib/pcp/config/pmie/config.default as part of pcp.rpm?

**Comment by goodwinos** [comment] 2020-11-25 22:03
Hi Marko, thanks for following up,

> Without not understanding all the nuances involved in this, how about also creating a sym link /etc/pcp/pmie/config.default -> /var/lib/pcp/config/pmie/config.default as part of pcp.rpm?

yes that would be desirable and effectively migrate the default to the /var location. However, what would we do with an existing /etc/pcp/pmie/config.default (even if it was only created by the faulty %post scriptlet in the spec)? It may have been edited by the user, we don't know, and it is the documented default location. So I opted to just leave that alone. Alternatively we could rename it to config.default.rpmsave and then replace it with a symlink, which I kind of prefer over having two defaults (one for users and one when pmieconf -c is used, which is a bit confusing IMO).

**Comment by myllynen** [comment] 2020-11-25 23:05
Yes, having two config files is IMHO very confusing - even after reading the above description for them last night. In the long-term there should be one configuration file but I'm not sure what would be the most acceptable way to get there. A big fat note on the man page? Check md5sum of the file and remove if matching the default? If not matching, create .rpmsave? At least on new installs create the sym link?

I realize that backward-compatibility is very important but this looks clearly like a bug fix, and, especially if PMIE would gain more traction, this would save everyone from lots of confusion in the future. But I guess we are on the same page here, the question is what the actual approach to solve this conundrum is still a bit open.

Thanks.

**Comment by goodwinos** [comment] 2020-11-26 22:49
related: b5f210ac0323622b5747e0b7cefa6bcffc037146

**Comment by goodwinos** [comment] 2020-11-26 22:58
I would like to get closure on this issue. I have a patch that does the following 

- the %post zeroconf scriptlet is changed to use the -f option to explicitly name the config it wants to update (in /var)
- the %post scriptlet for the base pcp package is changed to move any existing /etc/pcp/pmie/config.default to config.default.saved and echo a message. Then create a symlink /etc/pcp/pmie/config.default  -> /var/lib/pcp/config/pmie/config.default (if that link doesn't already exist). 
- TODO update pmieconf(1) man page.

```
diff --git a/build/rpm/pcp.spec.in b/build/rpm/pcp.spec.in
index 4462fe736..fda48e9fb 100755
--- a/build/rpm/pcp.spec.in
+++ b/build/rpm/pcp.spec.in
@@ -2734,6 +2734,7 @@ exit 0
 PCP_PMDAS_DIR=@pcp_pmdas_dir@
 PCP_SYSCONFIG_DIR=@pcp_sysconfig_dir@
 PCP_PMCDCONF_PATH=@pcp_pmcdconf_path@
+PCP_VAR_DIR=@pcp_var_dir@
 # auto-install important PMDAs for RH Support (if not present already)
 for PMDA in dm nfsclient openmetrics ; do
     if ! grep -q "$PMDA/pmda$PMDA" "$PCP_PMCDCONF_PATH"
@@ -2744,8 +2745,7 @@ done
 # increase default pmlogger recording frequency
 sed -i 's/^\#\ PMLOGGER_INTERVAL.*/PMLOGGER_INTERVAL=10/g' "$PCP_SYSCONFIG_DIR/pmlogger"
 # auto-enable these usually optional pmie rules
-pmieconf -c enable dmthin
-
+pmieconf -f "$PCP_VAR_DIR/config/pmie/config.default" -c enable dmthin
 %if "@enable_systemd@" == "true"
     systemctl restart pmcd >/dev/null 2>&1
     systemctl restart pmlogger >/dev/null 2>&1
@@ -3080,6 +3080,8 @@ fi
 PCP_PMNS_DIR=@pcp_var_dir@/pmns
 PCP_LOG_DIR=@pcp_log_dir@
 PCP_SA_DIR=@pcp_sa_dir@
+PCP_VAR_DIR=@pcp_var_dir@
+PCP_SYSCONF_DIR=@pcp_sysconf_dir@
 
 chown -R pcp:pcp "$PCP_LOG_DIR/pmcd" 2>/dev/null
 chown -R pcp:pcp "$PCP_LOG_DIR/pmlogger" 2>/dev/null
@@ -3088,6 +3090,18 @@ chown -R pcp:pcp "$PCP_LOG_DIR/pmie" 2>/dev/null
 chown -R pcp:pcp "$PCP_LOG_DIR/pmproxy" 2>/dev/null
 %{install_file "$PCP_PMNS_DIR" .NeedRebuild}
 %{install_file "$PCP_LOG_DIR/pmlogger" .NeedRewrite}
+
+# migrate old default pmie config, if any, and leave a symlink
+OLD_PMIE_CONFIG="$PCP_SYSCONF_DIR/pmie/config.default"
+PMIE_CONFIG="$PCP_VAR_DIR/config/pmie/config.default"
+if [ -f "$OLD_PMIE_CONFIG" -a ! -L "$OLD_PMIE_CONFIG" ]; then
+    mv "$OLD_PMIE_CONFIG" "$OLD_PMIE_CONFIG.rpmsave"
+    echo "Saved $OLD_PMIE_CONFIG.rpmsave"
+fi
+if [ ! -L "$OLD_PMIE_CONFIG" ]; then
+    ln -s "../../..$PMIE_CONFIG" "$OLD_PMIE_CONFIG"
+fi
+
 %if "@enable_systemd@" == "true"
     %systemd_postun_with_restart pmcd.service
     %systemd_post pmcd.service

```

... and similar for build/rpm/redhat.spec.

Does this look OK?

**Comment by natoscott** [comment] 2020-11-26 23:40
There should be no /etc entries - neither files nor symlinks - for *generated* configuration files.  If someone creates their own config, and places that in /etc - this is fine, and they can use it via absolute paths in control files (just like with pmlogger).

The root cause of this bug is that we accidentally, unintentionally created one - fix that, and over time the issue of folks getting confused by generated /etc files as well as /var files goes away.  Older releases will continue to leave this file here - its unused, and not a problem - however, we don't know if we generated it or they placed it there intentionally.

So, don't attempt to delete it or move it or  - it may have been legitimately created (interactively, not automated) using pmieconf, or places their by something like ansible/chef/puppet/etc and there may be a non-relative-path entry below /etc/pcp/pmie that references it, which would now be broken.

Trying to create/maintain/delete a symlink in lock-step with the generated file is going to be error prone.  We don't do it at all for pmlogger.  We don't do it for any of the other pmie processes (any relative path configs in /etc/pcp/pmie/control* files will generate configs, not just "local" and "config.default").  We shouldn't start doing it now IMO.

**Comment by goodwinos** [comment] 2020-11-27 00:01
ok thanks for the feedback, makes sense. So we'll just give pmieconf a -f path in %post zeroconf and that's it.

```
--- a/build/rpm/pcp.spec.in
+++ b/build/rpm/pcp.spec.in
@@ -2734,6 +2734,7 @@ exit 0
 PCP_PMDAS_DIR=@pcp_pmdas_dir@
 PCP_SYSCONFIG_DIR=@pcp_sysconfig_dir@
 PCP_PMCDCONF_PATH=@pcp_pmcdconf_path@
+PCP_VAR_DIR=@pcp_var_dir@
 # auto-install important PMDAs for RH Support (if not present already)
 for PMDA in dm nfsclient openmetrics ; do
     if ! grep -q "$PMDA/pmda$PMDA" "$PCP_PMCDCONF_PATH"
@@ -2744,8 +2745,7 @@ done
 # increase default pmlogger recording frequency
 sed -i 's/^\#\ PMLOGGER_INTERVAL.*/PMLOGGER_INTERVAL=10/g' "$PCP_SYSCONFIG_DIR/pmlogger"
 # auto-enable these usually optional pmie rules
-pmieconf -c enable dmthin
-
+pmieconf -f "$PCP_VAR_DIR/config/pmie/config.default" -c enable dmthin
```

**Comment by natoscott** [comment] 2020-11-27 00:09
It would be better if the -c option in pmieconf did this automatically.

```$ pmieconf --help |& head -4
Usage: pmieconf [options] [ command [args...] ]

Options:
  -c                    an automated pmie configuration by the system

```

**Comment by myllynen** [comment] 2020-11-27 08:15
Hmm, I now tried a fresh installation with the latest changes, I still see the config files under /etc and /var and additionally config.default.tmp also.

**Comment by goodwinos** [comment] 2020-11-27 10:36
> Hmm, I now tried a fresh installation with the latest changes, I still see the config files under /etc and /var and additionally config.default.tmp also.

That's expected - sorry. I have the fix (code change in pmieconf) but haven't committed it yet - we went out for dinner before I had the chance! I'll push it in the morning. Nathan's other change is related but doesn't address this actual issue (it addresses something much more subtle).

**Closed** 2020-11-30 03:46 UTC

**Comment by myllynen** [comment] 2020-12-02 21:41
Thanks, I'm happy to confirm the duplicate config file is gone now.

However, I see config.default.tmp left behind under /var, perhaps that could be also cleaned up while at it?

Thanks.

**Comment by natoscott** [comment] 2020-12-02 23:26
> However, I see config.default.tmp left behind under /var, perhaps that could be also cleaned up while at it?

@myllynen @goodwinos I see the cause of this issue - it's an inconsistency that's crept in between pmlogger_check (has the cleanup) and pmie_check (which does not).  Fix will follow shortly.
