### ISSUE TITLE
Metrics of pcp-pmda-apache are missing help texts

### ISSUE THREAD

**Issue by kurik** [performancecopilot/pcp#1256] opened 2021-05-10 15:05 UTC
Metrics of pcp-pmda-apache are missing help texts.

The following metrics of pcp-pmda-apache are missing online help texts.
This is output of ```pminfo -t``` filtered to metrics without a help text:
```
apache.total_accesses One-line Help: Error: One-line or help text is not available
apache.total_kbytes One-line Help: Error: One-line or help text is not available
apache.uptime One-line Help: Error: One-line or help text is not available
apache.requests_per_sec One-line Help: Error: One-line or help text is not available
apache.bytes_per_sec One-line Help: Error: One-line or help text is not available
apache.bytes_per_requests One-line Help: Error: One-line or help text is not available
apache.busy_servers One-line Help: Error: One-line or help text is not available
apache.idle_servers One-line Help: Error: One-line or help text is not available
apache.sb_waiting One-line Help: Error: One-line or help text is not available
apache.sb_starting One-line Help: Error: One-line or help text is not available
apache.sb_reading One-line Help: Error: One-line or help text is not available
apache.sb_writing_reply One-line Help: Error: One-line or help text is not available
apache.sb_keepalive One-line Help: Error: One-line or help text is not available
apache.sb_dns_lookup One-line Help: Error: One-line or help text is not available
apache.sb_logging One-line Help: Error: One-line or help text is not available
apache.sb_finishing One-line Help: Error: One-line or help text is not available
apache.sb_open_slot One-line Help: Error: One-line or help text is not available
apache.sb_closing One-line Help: Error: One-line or help text is not available
apache.sb_idle_cleanup One-line Help: Error: One-line or help text is not available
apache.uptime_s One-line Help: Error: One-line or help text is not available
```

The following metrics of pcp-pmda-apache are missing full help texts.
This is output of ```pminfo -T``` filtered to metrics without a help text:
```

apache.total_accesses
Full Help: Error: One-line or help text is not available

apache.total_kbytes
Full Help: Error: One-line or help text is not available

apache.uptime
Full Help: Error: One-line or help text is not available

apache.requests_per_sec
Full Help: Error: One-line or help text is not available

apache.bytes_per_sec
Full Help: Error: One-line or help text is not available

apache.bytes_per_requests
Full Help: Error: One-line or help text is not available

apache.busy_servers
Full Help: Error: One-line or help text is not available

apache.idle_servers
Full Help: Error: One-line or help text is not available

apache.sb_waiting
Full Help: Error: One-line or help text is not available

apache.sb_starting
Full Help: Error: One-line or help text is not available

apache.sb_reading
Full Help: Error: One-line or help text is not available

apache.sb_writing_reply
Full Help: Error: One-line or help text is not available

apache.sb_keepalive
Full Help: Error: One-line or help text is not available

apache.sb_dns_lookup
Full Help: Error: One-line or help text is not available

apache.sb_logging
Full Help: Error: One-line or help text is not available

apache.sb_finishing
Full Help: Error: One-line or help text is not available

apache.sb_open_slot
Full Help: Error: One-line or help text is not available

apache.sb_closing
Full Help: Error: One-line or help text is not available

apache.sb_idle_cleanup
Full Help: Error: One-line or help text is not available

apache.uptime_s
Full Help: Error: One-line or help text is not available
```

**Comment by kmcdonell** [comment] 2023-05-10 21:47
This issue is not understood, but it is not apparently reproducible.  The help text files for this PMDA are packaged and installed and appear to be available once the PMDA is in use by pmcd(1).
Closing the issue, please re-open if the problem is observed again.

**Closed by kmcdonell** 2023-05-10 21:47 UTC
