### ISSUE TITLE
Metrics of pcp-pmda-gfs2 are missing help texts.

### ISSUE THREAD

**Issue by kurik** [performancecopilot/pcp#1261] opened 2021-05-10 15:11 UTC
Metrics of pcp-pmda-gfs2 are missing help texts.

The following metrics of pcp-pmda-gfs2 are missing online help texts.
This is output of ```pminfo -t``` filtered to metrics without a help text:
```
gfs2.glocks.total One-line Help: Error: One-line or help text is not available
gfs2.glocks.shared One-line Help: Error: One-line or help text is not available
gfs2.glocks.unlocked One-line Help: Error: One-line or help text is not available
gfs2.glocks.deferred One-line Help: Error: One-line or help text is not available
gfs2.glocks.exclusive One-line Help: Error: One-line or help text is not available
gfs2.glocks.flags.locked One-line Help: Error: One-line or help text is not available
gfs2.glocks.flags.demote One-line Help: Error: One-line or help text is not available
gfs2.glocks.flags.demote_pending One-line Help: Error: One-line or help text is not available
gfs2.glocks.flags.demote_progress One-line Help: Error: One-line or help text is not available
gfs2.glocks.flags.dirty One-line Help: Error: One-line or help text is not available
gfs2.glocks.flags.log_flush One-line Help: Error: One-line or help text is not available
gfs2.glocks.flags.invalidate One-line Help: Error: One-line or help text is not available
gfs2.glocks.flags.reply_pending One-line Help: Error: One-line or help text is not available
gfs2.glocks.flags.initial One-line Help: Error: One-line or help text is not available
gfs2.glocks.flags.frozen One-line Help: Error: One-line or help text is not available
gfs2.glocks.flags.queued One-line Help: Error: One-line or help text is not available
gfs2.glocks.flags.object_attached One-line Help: Error: One-line or help text is not available
gfs2.glocks.flags.blocking_request One-line Help: Error: One-line or help text is not available
gfs2.glocks.flags.lru One-line Help: Error: One-line or help text is not available
gfs2.holders.total One-line Help: Error: One-line or help text is not available
gfs2.holders.shared One-line Help: Error: One-line or help text is not available
gfs2.holders.unlocked One-line Help: Error: One-line or help text is not available
gfs2.holders.defered One-line Help: Error: One-line or help text is not available
gfs2.holders.exclusive One-line Help: Error: One-line or help text is not available
gfs2.holders.flags.async One-line Help: Error: One-line or help text is not available
gfs2.holders.flags.any One-line Help: Error: One-line or help text is not available
gfs2.holders.flags.no_cache One-line Help: Error: One-line or help text is not available
gfs2.holders.flags.no_expire One-line Help: Error: One-line or help text is not available
gfs2.holders.flags.exact One-line Help: Error: One-line or help text is not available
gfs2.holders.flags.first One-line Help: Error: One-line or help text is not available
gfs2.holders.flags.holder One-line Help: Error: One-line or help text is not available
gfs2.holders.flags.priority One-line Help: Error: One-line or help text is not available
gfs2.holders.flags.try One-line Help: Error: One-line or help text is not available
gfs2.holders.flags.try_1cb One-line Help: Error: One-line or help text is not available
gfs2.holders.flags.wait One-line Help: Error: One-line or help text is not available
gfs2.glstats.total One-line Help: Error: One-line or help text is not available
gfs2.glstats.trans One-line Help: Error: One-line or help text is not available
gfs2.glstats.inode One-line Help: Error: One-line or help text is not available
gfs2.glstats.rgrp One-line Help: Error: One-line or help text is not available
gfs2.glstats.meta One-line Help: Error: One-line or help text is not available
gfs2.glstats.iopen One-line Help: Error: One-line or help text is not available
gfs2.glstats.flock One-line Help: Error: One-line or help text is not available
gfs2.glstats.quota One-line Help: Error: One-line or help text is not available
gfs2.glstats.journal One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_state_change.total One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_state_change.null_lock One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_state_change.concurrent_read One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_state_change.concurrent_write One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_state_change.protected_read One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_state_change.protected_write One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_state_change.exclusive One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_state_change.glocks.changed_target One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_state_change.glocks.missed_target One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_put.total One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_put.null_lock One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_put.concurrent_read One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_put.concurrent_write One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_put.protected_read One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_put.protected_write One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_put.exclusive One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.demote_rq.total One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.demote_rq.null_lock One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.demote_rq.concurrent_read One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.demote_rq.concurrent_write One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.demote_rq.protected_read One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.demote_rq.protected_write One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.demote_rq.exclusive One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.demote_rq.requested.remote One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.demote_rq.requested.local One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.promote.total One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.promote.first.null_lock One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.promote.first.concurrent_read One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.promote.first.concurrent_write One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.promote.first.protected_read One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.promote.first.protected_write One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.promote.first.exclusive One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.promote.other.null_lock One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.promote.other.concurrent_read One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.promote.other.concurrent_write One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.promote.other.protected_read One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.promote.other.protected_write One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.promote.other.exclusive One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_queue.total One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_queue.queue.total One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_queue.queue.null_lock One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_queue.queue.concurrent_read One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_queue.queue.concurrent_write One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_queue.queue.protected_read One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_queue.queue.protected_write One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_queue.queue.exclusive One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_queue.dequeue.total One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_queue.dequeue.null_lock One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_queue.dequeue.concurrent_read One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_queue.dequeue.concurrent_write One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_queue.dequeue.protected_read One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_queue.dequeue.protected_write One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_queue.dequeue.exclusive One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_lock_time.total One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_lock_time.trans One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_lock_time.inode One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_lock_time.rgrp One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_lock_time.meta One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_lock_time.iopen One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_lock_time.flock One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_lock_time.quota One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.glock_lock_time.journal One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.pin.total One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.pin.pin_total One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.pin.unpin_total One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.pin.longest_pinned One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.log_flush.total One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.log_block.total One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.ail_flush.total One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.block_alloc.total One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.block_alloc.free One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.block_alloc.used One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.block_alloc.dinode One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.block_alloc.unlinked One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.bmap.total One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.bmap.create One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.bmap.nocreate One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.rs.total One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.rs.del One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.rs.tdel One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.rs.ins One-line Help: Error: One-line or help text is not available
gfs2.tracepoints.rs.clm One-line Help: Error: One-line or help text is not available
gfs2.latency.grant.all One-line Help: Error: One-line or help text is not available
gfs2.latency.grant.null_lock One-line Help: Error: One-line or help text is not available
gfs2.latency.grant.concurrent_read One-line Help: Error: One-line or help text is not available
gfs2.latency.grant.concurrent_write One-line Help: Error: One-line or help text is not available
gfs2.latency.grant.protected_read One-line Help: Error: One-line or help text is not available
gfs2.latency.grant.protected_write One-line Help: Error: One-line or help text is not available
gfs2.latency.grant.exclusive One-line Help: Error: One-line or help text is not available
gfs2.latency.demote.all One-line Help: Error: One-line or help text is not available
gfs2.latency.demote.null_lock One-line Help: Error: One-line or help text is not available
gfs2.latency.demote.concurrent_read One-line Help: Error: One-line or help text is not available
gfs2.latency.demote.concurrent_write One-line Help: Error: One-line or help text is not available
gfs2.latency.demote.protected_read One-line Help: Error: One-line or help text is not available
gfs2.latency.demote.protected_write One-line Help: Error: One-line or help text is not available
gfs2.latency.demote.exclusive One-line Help: Error: One-line or help text is not available
gfs2.latency.queue.all One-line Help: Error: One-line or help text is not available
gfs2.latency.queue.null_lock One-line Help: Error: One-line or help text is not available
gfs2.latency.queue.concurrent_read One-line Help: Error: One-line or help text is not available
gfs2.latency.queue.concurrent_write One-line Help: Error: One-line or help text is not available
gfs2.latency.queue.protected_read One-line Help: Error: One-line or help text is not available
gfs2.latency.queue.protected_write One-line Help: Error: One-line or help text is not available
gfs2.latency.queue.exclusive One-line Help: Error: One-line or help text is not available
gfs2.control.buffer_size_kb One-line Help: Error: One-line or help text is not available
gfs2.control.global_tracing One-line Help: Error: One-line or help text is not available
gfs2.control.worst_glock One-line Help: Error: One-line or help text is not available
gfs2.control.latency One-line Help: Error: One-line or help text is not available
gfs2.control.glock_threshold One-line Help: Error: One-line or help text is not available
gfs2.control.tracepoints.all One-line Help: Error: One-line or help text is not available
gfs2.control.tracepoints.glock_state_change One-line Help: Error: One-line or help text is not available
gfs2.control.tracepoints.glock_put One-line Help: Error: One-line or help text is not available
gfs2.control.tracepoints.demote_rq One-line Help: Error: One-line or help text is not available
gfs2.control.tracepoints.promote One-line Help: Error: One-line or help text is not available
gfs2.control.tracepoints.glock_queue One-line Help: Error: One-line or help text is not available
gfs2.control.tracepoints.glock_lock_time One-line Help: Error: One-line or help text is not available
gfs2.control.tracepoints.pin One-line Help: Error: One-line or help text is not available
gfs2.control.tracepoints.log_flush One-line Help: Error: One-line or help text is not available
gfs2.control.tracepoints.log_blocks One-line Help: Error: One-line or help text is not available
gfs2.control.tracepoints.ail_flush One-line Help: Error: One-line or help text is not available
gfs2.control.tracepoints.block_alloc One-line Help: Error: One-line or help text is not available
gfs2.control.tracepoints.bmap One-line Help: Error: One-line or help text is not available
gfs2.control.tracepoints.rs One-line Help: Error: One-line or help text is not available
```

The following metrics of pcp-pmda-gfs2 are missing full help texts.
This is output of ```pminfo -T``` filtered to metrics without a help text:
```

gfs2.glocks.total
Full Help: Error: One-line or help text is not available

gfs2.glocks.shared
Full Help: Error: One-line or help text is not available

gfs2.glocks.unlocked
Full Help: Error: One-line or help text is not available

gfs2.glocks.deferred
Full Help: Error: One-line or help text is not available

gfs2.glocks.exclusive
Full Help: Error: One-line or help text is not available

gfs2.glocks.flags.locked
Full Help: Error: One-line or help text is not available

gfs2.glocks.flags.demote
Full Help: Error: One-line or help text is not available

gfs2.glocks.flags.demote_pending
Full Help: Error: One-line or help text is not available

gfs2.glocks.flags.demote_progress
Full Help: Error: One-line or help text is not available

gfs2.glocks.flags.dirty
Full Help: Error: One-line or help text is not available

gfs2.glocks.flags.log_flush
Full Help: Error: One-line or help text is not available

gfs2.glocks.flags.invalidate
Full Help: Error: One-line or help text is not available

gfs2.glocks.flags.reply_pending
Full Help: Error: One-line or help text is not available

gfs2.glocks.flags.initial
Full Help: Error: One-line or help text is not available

gfs2.glocks.flags.frozen
Full Help: Error: One-line or help text is not available

gfs2.glocks.flags.queued
Full Help: Error: One-line or help text is not available

gfs2.glocks.flags.object_attached
Full Help: Error: One-line or help text is not available

gfs2.glocks.flags.blocking_request
Full Help: Error: One-line or help text is not available

gfs2.glocks.flags.lru
Full Help: Error: One-line or help text is not available

gfs2.holders.total
Full Help: Error: One-line or help text is not available

gfs2.holders.shared
Full Help: Error: One-line or help text is not available

gfs2.holders.unlocked
Full Help: Error: One-line or help text is not available

gfs2.holders.defered
Full Help: Error: One-line or help text is not available

gfs2.holders.exclusive
Full Help: Error: One-line or help text is not available

gfs2.holders.flags.async
Full Help: Error: One-line or help text is not available

gfs2.holders.flags.any
Full Help: Error: One-line or help text is not available

gfs2.holders.flags.no_cache
Full Help: Error: One-line or help text is not available

gfs2.holders.flags.no_expire
Full Help: Error: One-line or help text is not available

gfs2.holders.flags.exact
Full Help: Error: One-line or help text is not available

gfs2.holders.flags.first
Full Help: Error: One-line or help text is not available

gfs2.holders.flags.holder
Full Help: Error: One-line or help text is not available

gfs2.holders.flags.priority
Full Help: Error: One-line or help text is not available

gfs2.holders.flags.try
Full Help: Error: One-line or help text is not available

gfs2.holders.flags.try_1cb
Full Help: Error: One-line or help text is not available

gfs2.holders.flags.wait
Full Help: Error: One-line or help text is not available

gfs2.glstats.total
Full Help: Error: One-line or help text is not available

gfs2.glstats.trans
Full Help: Error: One-line or help text is not available

gfs2.glstats.inode
Full Help: Error: One-line or help text is not available

gfs2.glstats.rgrp
Full Help: Error: One-line or help text is not available

gfs2.glstats.meta
Full Help: Error: One-line or help text is not available

gfs2.glstats.iopen
Full Help: Error: One-line or help text is not available

gfs2.glstats.flock
Full Help: Error: One-line or help text is not available

gfs2.glstats.quota
Full Help: Error: One-line or help text is not available

gfs2.glstats.journal
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_state_change.total
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_state_change.null_lock
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_state_change.concurrent_read
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_state_change.concurrent_write
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_state_change.protected_read
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_state_change.protected_write
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_state_change.exclusive
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_state_change.glocks.changed_target
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_state_change.glocks.missed_target
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_put.total
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_put.null_lock
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_put.concurrent_read
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_put.concurrent_write
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_put.protected_read
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_put.protected_write
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_put.exclusive
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.demote_rq.total
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.demote_rq.null_lock
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.demote_rq.concurrent_read
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.demote_rq.concurrent_write
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.demote_rq.protected_read
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.demote_rq.protected_write
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.demote_rq.exclusive
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.demote_rq.requested.remote
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.demote_rq.requested.local
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.promote.total
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.promote.first.null_lock
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.promote.first.concurrent_read
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.promote.first.concurrent_write
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.promote.first.protected_read
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.promote.first.protected_write
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.promote.first.exclusive
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.promote.other.null_lock
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.promote.other.concurrent_read
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.promote.other.concurrent_write
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.promote.other.protected_read
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.promote.other.protected_write
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.promote.other.exclusive
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_queue.total
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_queue.queue.total
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_queue.queue.null_lock
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_queue.queue.concurrent_read
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_queue.queue.concurrent_write
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_queue.queue.protected_read
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_queue.queue.protected_write
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_queue.queue.exclusive
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_queue.dequeue.total
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_queue.dequeue.null_lock
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_queue.dequeue.concurrent_read
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_queue.dequeue.concurrent_write
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_queue.dequeue.protected_read
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_queue.dequeue.protected_write
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_queue.dequeue.exclusive
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_lock_time.total
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_lock_time.trans
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_lock_time.inode
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_lock_time.rgrp
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_lock_time.meta
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_lock_time.iopen
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_lock_time.flock
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_lock_time.quota
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.glock_lock_time.journal
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.pin.total
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.pin.pin_total
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.pin.unpin_total
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.pin.longest_pinned
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.log_flush.total
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.log_block.total
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.ail_flush.total
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.block_alloc.total
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.block_alloc.free
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.block_alloc.used
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.block_alloc.dinode
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.block_alloc.unlinked
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.bmap.total
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.bmap.create
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.bmap.nocreate
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.rs.total
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.rs.del
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.rs.tdel
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.rs.ins
Full Help: Error: One-line or help text is not available

gfs2.tracepoints.rs.clm
Full Help: Error: One-line or help text is not available

gfs2.latency.grant.all
Full Help: Error: One-line or help text is not available

gfs2.latency.grant.null_lock
Full Help: Error: One-line or help text is not available

gfs2.latency.grant.concurrent_read
Full Help: Error: One-line or help text is not available

gfs2.latency.grant.concurrent_write
Full Help: Error: One-line or help text is not available

gfs2.latency.grant.protected_read
Full Help: Error: One-line or help text is not available

gfs2.latency.grant.protected_write
Full Help: Error: One-line or help text is not available

gfs2.latency.grant.exclusive
Full Help: Error: One-line or help text is not available

gfs2.latency.demote.all
Full Help: Error: One-line or help text is not available

gfs2.latency.demote.null_lock
Full Help: Error: One-line or help text is not available

gfs2.latency.demote.concurrent_read
Full Help: Error: One-line or help text is not available

gfs2.latency.demote.concurrent_write
Full Help: Error: One-line or help text is not available

gfs2.latency.demote.protected_read
Full Help: Error: One-line or help text is not available

gfs2.latency.demote.protected_write
Full Help: Error: One-line or help text is not available

gfs2.latency.demote.exclusive
Full Help: Error: One-line or help text is not available

gfs2.latency.queue.all
Full Help: Error: One-line or help text is not available

gfs2.latency.queue.null_lock
Full Help: Error: One-line or help text is not available

gfs2.latency.queue.concurrent_read
Full Help: Error: One-line or help text is not available

gfs2.latency.queue.concurrent_write
Full Help: Error: One-line or help text is not available

gfs2.latency.queue.protected_read
Full Help: Error: One-line or help text is not available

gfs2.latency.queue.protected_write
Full Help: Error: One-line or help text is not available

gfs2.latency.queue.exclusive
Full Help: Error: One-line or help text is not available

gfs2.control.buffer_size_kb
Full Help: Error: One-line or help text is not available

gfs2.control.global_tracing
Full Help: Error: One-line or help text is not available

gfs2.control.worst_glock
Full Help: Error: One-line or help text is not available

gfs2.control.latency
Full Help: Error: One-line or help text is not available

gfs2.control.glock_threshold
Full Help: Error: One-line or help text is not available

gfs2.control.tracepoints.all
Full Help: Error: One-line or help text is not available

gfs2.control.tracepoints.glock_state_change
Full Help: Error: One-line or help text is not available

gfs2.control.tracepoints.glock_put
Full Help: Error: One-line or help text is not available

gfs2.control.tracepoints.demote_rq
Full Help: Error: One-line or help text is not available

gfs2.control.tracepoints.promote
Full Help: Error: One-line or help text is not available

gfs2.control.tracepoints.glock_queue
Full Help: Error: One-line or help text is not available

gfs2.control.tracepoints.glock_lock_time
Full Help: Error: One-line or help text is not available

gfs2.control.tracepoints.pin
Full Help: Error: One-line or help text is not available

gfs2.control.tracepoints.log_flush
Full Help: Error: One-line or help text is not available

gfs2.control.tracepoints.log_blocks
Full Help: Error: One-line or help text is not available

gfs2.control.tracepoints.ail_flush
Full Help: Error: One-line or help text is not available

gfs2.control.tracepoints.block_alloc
Full Help: Error: One-line or help text is not available

gfs2.control.tracepoints.bmap
Full Help: Error: One-line or help text is not available

gfs2.control.tracepoints.rs
Full Help: Error: One-line or help text is not available
```

**Comment by kmcdonell** [comment] 2023-05-10 21:45
This issue is not understood, but it is not apparently reproducible.  The help text files for this PMDA are packaged and installed and appear to be available once the PMDA is in use by pmcd(1).
Closing the issue, please re-open if the problem is observed again.

**Closed by kmcdonell** 2023-05-10 21:45 UTC
