### ISSUE TITLE
pmchart crash on OSX with certain archive

### ISSUE THREAD

**Issue by tallpsmith** [performancecopilot/pcp#35] opened 2015-08-10 06:48 UTC
I've tried this with the latest pmchart (3.10.6), but I get this crash pretty reliably as I scroll around time ranges with a specific archive.

    [ app2 ]$ pmchart -z -a 20150807.0
    pmchart(13806,0x7fff7e625300) malloc: *** error for object 0x1028caf80: pointer being freed was not allocated
    *** set a breakpoint in malloc_error_break to debug
    Abort trap: 6```

I'll attach the actual OSX Debug window data as a separate file.  The archive I think I'll have to provide externally rather than here.

**Comment by tallpsmith** [comment] 2015-08-10 06:50
https://gist.github.com/tallpsmith/d0b2d6acdeff177a69a1

**Comment by tallpsmith** [comment] 2015-08-10 06:55
Leaving a reference for myself, this was app2 in AUH `20150807`

**Comment by kmcdonell** [comment] 2015-08-10 21:27
Thanks for that Paul ... especially as it lands in my lap via the much maligned interp.c.

I would expect this to have nothing to do with pmchart, other than guilt by association.

But I will need some additional information to prosecute this:
1. the archive (maybe under NDA if the information is sensitive)
2. the metrics you were monitoring ... if these came from a pmchart config, then that file would help and it would help to know if you added or deleted metrics and/or charts between the start of pmchart and the failure
3. update interval (default, or -t from command line, or changed via time control widget)
4. travelling forwards or backwards in the archive
5. position in the archive ... just playing forwards from the start, or just playing backwards from the end, or -S, -O, -A or -T command line options, or drag-n-drop the time line via the time control widget)

Unfortunately there are many levers that influence the interpolation code, and it helps to have the fullest possible picture of all of them leading up to the kaboom.

**Comment by kmcdonell** [comment] 2015-08-10 21:28
Oh, and
6. which version of PCP is this?

**Comment by tallpsmith** [comment] 2015-08-11 02:50
pmlogger was running on 3.6.5-1, pmchart running on the latest build (downloaded yesterday), 3.10.6.

I'll setup a step by step guide if I can, and email you the archive privately.

**Comment by tallpsmith** [comment] 2015-08-11 03:03
Here's the gist with the command to run, plus the chart file I created, when I run the command with this chart against the archive (emailed to you), it crashes immediately (I don't see anything, just a crash).

https://gist.github.com/tallpsmith/06d6638abc4e1d170d96

**Comment by tallpsmith** [comment] 2015-09-07 10:53
I'll just say that this is currently affecting me _a lot_.  I wouldn't normally nag, but I'm struggling to work around this on OSX, doesn't seem to affect others on Linux here for some reason.  

Any progress would be met with a happy dance.

**Comment by kmcdonell** [comment] 2015-09-09 08:51
Paul I'm in Europe at the moment ... no PCP bandwidth for another couple of weeks I'm afraid.

-----Original Message-----

**Comment by natoscott** [comment] 2015-09-09 22:02
@kmcdonell Paul has sent me the archive too now, hoping to diagnose & fix within a week.

**Comment by natoscott** [comment] 2015-09-11 08:36
| Any progress would be met with a happy dance.

I've reproduced the problem, debugged a bit (ohhhh man, interp.c) and have an initial workaround which I'm testing at the moment to see whether it might serve for next weeks release.  I'm not 100% sure of the intention of some parts of the affected code (in libpcp/src/interp.c cache_read) so the long-term fix will very likely need to wait Kens input.

But, I can definitely replay that archive now on Mac OS X (its all in libpcp memory management code, and nothing to do with archive format changing, or anything like that, as was wondered earlier).

cheers.

**Comment by natoscott** [comment] 2015-09-14 08:02
Paul, could you try the dmg file I've put at ftp://ftp.pcp.io/projects/pcp/download/pcp-3.10.7-rc1.dmg and see how that pmchart fares for you?  Seems to be working again for me for your test case.

I git-bisect'ed back to commit 7881fd51d34 ("libpcp pdubuf: rewrite using <search.h> binary trees") which is a libpcp pdubuf performance optimisation only used by pmwebd currently.  I believe it may have something to do with buffer unpinning of cache'd pmResult valuesets in the interp.c cache_read() code, but not sure beyond that.

Like you, I'm also only seeing it fail on Mac OS X - perhaps the memory allocation strategies there are circumventing the logic at the start of __pmFreeResultValueSets() - again, not clear.  I'll add a pointer to some trace logs here shortly so others can have a peek too.

cheers.

**Comment by natoscott** [comment] 2015-09-14 08:09
https://gist.github.com/natoscott/bd4ed6c24470faaef057

**Comment by natoscott** [comment] 2015-09-14 08:14
To clarify a little, the dmg above is a build with the libpcp commit above reverted - there is no known fix beyond that at this stage.

**Comment by tallpsmith** [comment] 2015-09-14 09:10
I'm on leave until next Monday up in Sunny Queensland.ill try when I get
back.

Thanks heaps for looking into it.

**Comment by natoscott** [comment] 2015-09-15 04:38
I've found a simpler reproducer using pmdumptext, and a smaller version of Paul's production data.  I've anonymised that archive and committed it as qa/archives/small and added qa/816 which reproduces the problem using pmdumptext.

For reference, I'll add a couple of gists of the full before/after debug logs, shortly showing failure vs success to help triangulate where things go astray.

I've temporarily backed out the libpcp optimization behind the regression for pcp-3.10.7 (which is about to release in a day or so).

**Comment by natoscott** [comment] 2015-09-15 04:43
Failing case - https://gist.github.com/natoscott/f8288c218c1e06ede622
Passing case - https://gist.github.com/natoscott/00bd07a41db20e2c6efd

See qa/816 for additional details (and/or the commands at head of each gist)

**Comment by tallpsmith** [comment] 2015-09-21 01:31
Thanks Nato.  just downloaded -7 today and seems to be working a treat!  Sanity restored, many thanks.

**Comment by natoscott** [comment] 2015-09-21 01:33
No problem, thanks Paul.

**Closed by natoscott** 2015-09-21 01:33 UTC
Labels: bug
