### ISSUE TITLE
Metrics of pcp-pmda-activemq are missing help texts

### ISSUE THREAD

**Issue by kurik** [performancecopilot/pcp#1255] opened 2021-05-10 15:05 UTC
Metrics of pcp-pmda-activemq are missing help texts.

The following metrics of pcp-pmda-activemq are missing online help texts.
This is output of ```pminfo -t``` filtered to metrics without a help text:
```
activemq.jvm.garbage_collection.ps_scavenge.collection_count []
activemq.jvm.garbage_collection.ps_scavenge.collection_time []
activemq.jvm.garbage_collection.ps_mark_sweep.collection_count []
activemq.jvm.garbage_collection.ps_mark_sweep.collection_time []
activemq.jvm.memory.heap_memory_usage.used []
activemq.jvm.memory.heap_memory_usage.committed []
activemq.jvm.memory.heap_memory_usage.init []
activemq.jvm.memory.heap_memory_usage.max []
activemq.jvm.memory.non_heap_memory_usage.init []
activemq.jvm.memory.non_heap_memory_usage.max []
activemq.jvm.memory.non_heap_memory_usage.committed []
activemq.jvm.memory.non_heap_memory_usage.used []
activemq.jvm.memory_pool.code_cache.usage.max []
activemq.jvm.memory_pool.code_cache.usage.committed []
activemq.jvm.memory_pool.code_cache.usage.init []
activemq.jvm.memory_pool.code_cache.usage.used []
activemq.jvm.memory_pool.code_cache.peak_usage.max []
activemq.jvm.memory_pool.code_cache.peak_usage.committed []
activemq.jvm.memory_pool.code_cache.peak_usage.init []
activemq.jvm.memory_pool.code_cache.peak_usage.used []
activemq.jvm.memory_pool.ps_perm_gen.collection_usage.max []
activemq.jvm.memory_pool.ps_perm_gen.collection_usage.committed []
activemq.jvm.memory_pool.ps_perm_gen.collection_usage.init []
activemq.jvm.memory_pool.ps_perm_gen.collection_usage.used []
activemq.jvm.memory_pool.ps_perm_gen.peak_usage.max []
activemq.jvm.memory_pool.ps_perm_gen.peak_usage.used []
activemq.jvm.memory_pool.ps_perm_gen.peak_usage.init []
activemq.jvm.memory_pool.ps_perm_gen.peak_usage.committed []
activemq.jvm.memory_pool.ps_perm_gen.usage.committed []
activemq.jvm.memory_pool.ps_perm_gen.usage.max []
activemq.jvm.memory_pool.ps_perm_gen.usage.used []
activemq.jvm.memory_pool.ps_perm_gen.usage.init []
activemq.jvm.memory_pool.ps_eden_space.peak_usage.used []
activemq.jvm.memory_pool.ps_eden_space.peak_usage.max []
activemq.jvm.memory_pool.ps_eden_space.peak_usage.committed []
activemq.jvm.memory_pool.ps_eden_space.peak_usage.init []
activemq.jvm.memory_pool.ps_eden_space.collection_usage.max []
activemq.jvm.memory_pool.ps_eden_space.collection_usage.committed []
activemq.jvm.memory_pool.ps_eden_space.collection_usage.used []
activemq.jvm.memory_pool.ps_eden_space.collection_usage.init []
activemq.jvm.memory_pool.ps_eden_space.usage.committed []
activemq.jvm.memory_pool.ps_eden_space.usage.used []
activemq.jvm.memory_pool.ps_eden_space.usage.max []
activemq.jvm.memory_pool.ps_eden_space.usage.init []
activemq.jvm.memory_pool.ps_survivor_space.collection_usage.committed []
activemq.jvm.memory_pool.ps_survivor_space.collection_usage.max []
activemq.jvm.memory_pool.ps_survivor_space.collection_usage.used []
activemq.jvm.memory_pool.ps_survivor_space.collection_usage.init []
activemq.jvm.memory_pool.ps_survivor_space.usage.init []
activemq.jvm.memory_pool.ps_survivor_space.usage.committed []
activemq.jvm.memory_pool.ps_survivor_space.usage.max []
activemq.jvm.memory_pool.ps_survivor_space.usage.used []
activemq.jvm.memory_pool.ps_survivor_space.peak_usage.used []
activemq.jvm.memory_pool.ps_survivor_space.peak_usage.committed []
activemq.jvm.memory_pool.ps_survivor_space.peak_usage.max []
activemq.jvm.memory_pool.ps_survivor_space.peak_usage.init []
activemq.jvm.memory_pool.ps_old_gen.peak_usage.committed []
activemq.jvm.memory_pool.ps_old_gen.peak_usage.used []
activemq.jvm.memory_pool.ps_old_gen.peak_usage.max []
activemq.jvm.memory_pool.ps_old_gen.peak_usage.init []
activemq.jvm.memory_pool.ps_old_gen.collection_usage.committed []
activemq.jvm.memory_pool.ps_old_gen.collection_usage.max []
activemq.jvm.memory_pool.ps_old_gen.collection_usage.init []
activemq.jvm.memory_pool.ps_old_gen.collection_usage.used []
activemq.jvm.memory_pool.ps_old_gen.usage.init []
activemq.jvm.memory_pool.ps_old_gen.usage.used []
activemq.jvm.memory_pool.ps_old_gen.usage.committed []
activemq.jvm.memory_pool.ps_old_gen.usage.max []
```

The following metrics of pcp-pmda-activemq are missing full help texts.
This is output of ```pminfo -T``` filtered to metrics without a help text:
```

activemq.jvm.garbage_collection.ps_scavenge.collection_count
Help: <empty entry>

activemq.jvm.garbage_collection.ps_scavenge.collection_time
Help: <empty entry>

activemq.jvm.garbage_collection.ps_mark_sweep.collection_count
Help: <empty entry>

activemq.jvm.garbage_collection.ps_mark_sweep.collection_time
Help: <empty entry>

activemq.jvm.memory.heap_memory_usage.used
Help: <empty entry>

activemq.jvm.memory.heap_memory_usage.committed
Help: <empty entry>

activemq.jvm.memory.heap_memory_usage.init
Help: <empty entry>

activemq.jvm.memory.heap_memory_usage.max
Help: <empty entry>

activemq.jvm.memory.non_heap_memory_usage.init
Help: <empty entry>

activemq.jvm.memory.non_heap_memory_usage.max
Help: <empty entry>

activemq.jvm.memory.non_heap_memory_usage.committed
Help: <empty entry>

activemq.jvm.memory.non_heap_memory_usage.used
Help: <empty entry>

activemq.jvm.memory_pool.code_cache.usage.max
Help: <empty entry>

activemq.jvm.memory_pool.code_cache.usage.committed
Help: <empty entry>

activemq.jvm.memory_pool.code_cache.usage.init
Help: <empty entry>

activemq.jvm.memory_pool.code_cache.usage.used
Help: <empty entry>

activemq.jvm.memory_pool.code_cache.peak_usage.max
Help: <empty entry>

activemq.jvm.memory_pool.code_cache.peak_usage.committed
Help: <empty entry>

activemq.jvm.memory_pool.code_cache.peak_usage.init
Help: <empty entry>

activemq.jvm.memory_pool.code_cache.peak_usage.used
Help: <empty entry>

activemq.jvm.memory_pool.ps_perm_gen.collection_usage.max
Help: <empty entry>

activemq.jvm.memory_pool.ps_perm_gen.collection_usage.committed
Help: <empty entry>

activemq.jvm.memory_pool.ps_perm_gen.collection_usage.init
Help: <empty entry>

activemq.jvm.memory_pool.ps_perm_gen.collection_usage.used
Help: <empty entry>

activemq.jvm.memory_pool.ps_perm_gen.peak_usage.max
Help: <empty entry>

activemq.jvm.memory_pool.ps_perm_gen.peak_usage.used
Help: <empty entry>

activemq.jvm.memory_pool.ps_perm_gen.peak_usage.init
Help: <empty entry>

activemq.jvm.memory_pool.ps_perm_gen.peak_usage.committed
Help: <empty entry>

activemq.jvm.memory_pool.ps_perm_gen.usage.committed
Help: <empty entry>

activemq.jvm.memory_pool.ps_perm_gen.usage.max
Help: <empty entry>

activemq.jvm.memory_pool.ps_perm_gen.usage.used
Help: <empty entry>

activemq.jvm.memory_pool.ps_perm_gen.usage.init
Help: <empty entry>

activemq.jvm.memory_pool.ps_eden_space.peak_usage.used
Help: <empty entry>

activemq.jvm.memory_pool.ps_eden_space.peak_usage.max
Help: <empty entry>

activemq.jvm.memory_pool.ps_eden_space.peak_usage.committed
Help: <empty entry>

activemq.jvm.memory_pool.ps_eden_space.peak_usage.init
Help: <empty entry>

activemq.jvm.memory_pool.ps_eden_space.collection_usage.max
Help: <empty entry>

activemq.jvm.memory_pool.ps_eden_space.collection_usage.committed
Help: <empty entry>

activemq.jvm.memory_pool.ps_eden_space.collection_usage.used
Help: <empty entry>

activemq.jvm.memory_pool.ps_eden_space.collection_usage.init
Help: <empty entry>

activemq.jvm.memory_pool.ps_eden_space.usage.committed
Help: <empty entry>

activemq.jvm.memory_pool.ps_eden_space.usage.used
Help: <empty entry>

activemq.jvm.memory_pool.ps_eden_space.usage.max
Help: <empty entry>

activemq.jvm.memory_pool.ps_eden_space.usage.init
Help: <empty entry>

activemq.jvm.memory_pool.ps_survivor_space.collection_usage.committed
Help: <empty entry>

activemq.jvm.memory_pool.ps_survivor_space.collection_usage.max
Help: <empty entry>

activemq.jvm.memory_pool.ps_survivor_space.collection_usage.used
Help: <empty entry>

activemq.jvm.memory_pool.ps_survivor_space.collection_usage.init
Help: <empty entry>

activemq.jvm.memory_pool.ps_survivor_space.usage.init
Help: <empty entry>

activemq.jvm.memory_pool.ps_survivor_space.usage.committed
Help: <empty entry>

activemq.jvm.memory_pool.ps_survivor_space.usage.max
Help: <empty entry>

activemq.jvm.memory_pool.ps_survivor_space.usage.used
Help: <empty entry>

activemq.jvm.memory_pool.ps_survivor_space.peak_usage.used
Help: <empty entry>

activemq.jvm.memory_pool.ps_survivor_space.peak_usage.committed
Help: <empty entry>

activemq.jvm.memory_pool.ps_survivor_space.peak_usage.max
Help: <empty entry>

activemq.jvm.memory_pool.ps_survivor_space.peak_usage.init
Help: <empty entry>

activemq.jvm.memory_pool.ps_old_gen.peak_usage.committed
Help: <empty entry>

activemq.jvm.memory_pool.ps_old_gen.peak_usage.used
Help: <empty entry>

activemq.jvm.memory_pool.ps_old_gen.peak_usage.max
Help: <empty entry>

activemq.jvm.memory_pool.ps_old_gen.peak_usage.init
Help: <empty entry>

activemq.jvm.memory_pool.ps_old_gen.collection_usage.committed
Help: <empty entry>

activemq.jvm.memory_pool.ps_old_gen.collection_usage.max
Help: <empty entry>

activemq.jvm.memory_pool.ps_old_gen.collection_usage.init
Help: <empty entry>

activemq.jvm.memory_pool.ps_old_gen.collection_usage.used
Help: <empty entry>

activemq.jvm.memory_pool.ps_old_gen.usage.init
Help: <empty entry>

activemq.jvm.memory_pool.ps_old_gen.usage.used
Help: <empty entry>

activemq.jvm.memory_pool.ps_old_gen.usage.committed
Help: <empty entry>

activemq.jvm.memory_pool.ps_old_gen.usage.max
Help: <empty entry>
```

**Comment by kmcdonell** [comment] 2023-05-10 21:52
This issue is not understood, but it is not apparently reproducible.  The help text files for this PMDA are packaged and installed and appear to be available once the PMDA is in use by pmcd(1).
Closing the issue, please re-open if the problem is observed again.

**Closed by kmcdonell** 2023-05-10 21:52 UTC
