### ISSUE TITLE
Metrics of pcp-pmda-systemd are missing help texts.

### ISSUE THREAD

**Issue by kurik** [performancecopilot/pcp#1280] opened 2021-05-10 16:32 UTC
Metrics of pcp-pmda-systemd are missing help texts.

The following metrics of pcp-pmda-systemd are missing online help texts.
This is output of ```pminfo -t``` filtered to metrics without a help text:
```
systemd.numclients One-line Help: Error: One-line or help text is not available
systemd.maxmem One-line Help: Error: One-line or help text is not available
systemd.journal.records One-line Help: Error: One-line or help text is not available
systemd.journal.records_raw One-line Help: Error: One-line or help text is not available
systemd.journal.count One-line Help: Error: One-line or help text is not available
systemd.journal.bytes One-line Help: Error: One-line or help text is not available
systemd.journal.field.cursor One-line Help: Error: One-line or help text is not available
systemd.journal.field.string One-line Help: Error: One-line or help text is not available
systemd.journal.field.blob One-line Help: Error: One-line or help text is not available
```

The following metrics of pcp-pmda-systemd are missing full help texts.
This is output of ```pminfo -T``` filtered to metrics without a help text:
```

systemd.numclients
Full Help: Error: One-line or help text is not available

systemd.maxmem
Full Help: Error: One-line or help text is not available

systemd.journal.records
Full Help: Error: One-line or help text is not available

systemd.journal.records_raw
Full Help: Error: One-line or help text is not available

systemd.journal.count
Full Help: Error: One-line or help text is not available

systemd.journal.bytes
Full Help: Error: One-line or help text is not available

systemd.journal.field.cursor
Full Help: Error: One-line or help text is not available

systemd.journal.field.string
Full Help: Error: One-line or help text is not available

systemd.journal.field.blob
Full Help: Error: One-line or help text is not available
```

**Comment by kmcdonell** [comment] 2023-05-10 21:36
This issue is not understood, but it is not apparently reproducible.  The help text files for this PMDA are packaged and installed and appear to be available once the PMDA is in use by pmcd(1).
Closing the issue, please re-open if the problem is observed again.

**Closed by kmcdonell** 2023-05-10 21:36 UTC
