### ISSUE TITLE
Metrics of pcp-pmda-bash are missing help texts

### ISSUE THREAD

**Issue by kurik** [performancecopilot/pcp#1257] opened 2021-05-10 15:06 UTC
Metrics of pcp-pmda-bash are missing help texts.

The following metrics of pcp-pmda-bash are missing online help texts.
This is output of ```pminfo -t``` filtered to metrics without a help text:
```
bash.xtrace.numclients One-line Help: Error: One-line or help text is not available
bash.xtrace.maxmem One-line Help: Error: One-line or help text is not available
bash.xtrace.queuemem One-line Help: Error: One-line or help text is not available
bash.xtrace.count One-line Help: Error: One-line or help text is not available
bash.xtrace.records One-line Help: Error: One-line or help text is not available
bash.xtrace.parameters.pid One-line Help: Error: One-line or help text is not available
bash.xtrace.parameters.parent One-line Help: Error: One-line or help text is not available
bash.xtrace.parameters.lineno One-line Help: Error: One-line or help text is not available
bash.xtrace.parameters.function One-line Help: Error: One-line or help text is not available
bash.xtrace.parameters.command One-line Help: Error: One-line or help text is not available
```

The following metrics of pcp-pmda-bash are missing full help texts.
This is output of ```pminfo -T``` filtered to metrics without a help text:
```

bash.xtrace.numclients
Full Help: Error: One-line or help text is not available

bash.xtrace.maxmem
Full Help: Error: One-line or help text is not available

bash.xtrace.queuemem
Full Help: Error: One-line or help text is not available

bash.xtrace.count
Full Help: Error: One-line or help text is not available

bash.xtrace.records
Full Help: Error: One-line or help text is not available

bash.xtrace.parameters.pid
Full Help: Error: One-line or help text is not available

bash.xtrace.parameters.parent
Full Help: Error: One-line or help text is not available

bash.xtrace.parameters.lineno
Full Help: Error: One-line or help text is not available

bash.xtrace.parameters.function
Full Help: Error: One-line or help text is not available

bash.xtrace.parameters.command
Full Help: Error: One-line or help text is not available
```

**Comment by kmcdonell** [comment] 2023-05-10 21:46
This issue is not understood, but it is not apparently reproducible.  The help text files for this PMDA are packaged and installed and appear to be available once the PMDA is in use by pmcd(1).
Closing the issue, please re-open if the problem is observed again.

**Closed by kmcdonell** 2023-05-10 21:46 UTC
