### ISSUE TITLE
Metrics of pcp-pmda-summary are missing help texts.

### ISSUE THREAD

**Issue by kurik** [performancecopilot/pcp#1279] opened 2021-05-10 16:32 UTC
Metrics of pcp-pmda-summary are missing help texts.

The following metrics of pcp-pmda-summary are missing online help texts.
This is output of ```pminfo -t``` filtered to metrics without a help text:
```
summary.cpu.util One-line Help: Error: One-line or help text is not available
summary.cpu.busy One-line Help: Error: One-line or help text is not available
summary.disk.iops One-line Help: Error: One-line or help text is not available
summary.disk.busy One-line Help: Error: One-line or help text is not available
summary.netif.packets One-line Help: Error: One-line or help text is not available
summary.netif.busy One-line Help: Error: One-line or help text is not available
```

The following metrics of pcp-pmda-summary are missing full help texts.
This is output of ```pminfo -T``` filtered to metrics without a help text:
```

summary.cpu.util
Full Help: Error: One-line or help text is not available

summary.cpu.busy
Full Help: Error: One-line or help text is not available

summary.disk.iops
Full Help: Error: One-line or help text is not available

summary.disk.busy
Full Help: Error: One-line or help text is not available

summary.netif.packets
Full Help: Error: One-line or help text is not available

summary.netif.busy
Full Help: Error: One-line or help text is not available
```

**Comment by kmcdonell** [comment] 2023-05-10 21:36
This issue is not understood, but it is not apparently reproducible.  The help text files for this PMDA are packaged and installed and appear to be available once the PMDA is in use by pmcd(1).
Closing the issue, please re-open if the problem is observed again.

**Closed by kmcdonell** 2023-05-10 21:36 UTC
