### ISSUE TITLE
Building on Ubuntu Precise fails on LOGIMPORT.3.gz

### ISSUE THREAD

**Issue by gwillem** [performancecopilot/pcp#8] opened 2015-04-09 12:58 UTC
Vanilla Ubuntu Precise install with required deps installed. 

```
dh_install --sourcedir=debian/pcp
cp: cannot stat `debian/pcp/usr/share/man/man3/LOGIMPORT.3.gz': No such file or directory
dh_install: cp -a debian/pcp/usr/share/man/man3/LOGIMPORT.3.gz debian/libpcp3-dev//usr/share/man/man3/ returned exit code 1
make: *** [binary-arch] Error 2
```
I have not figured out why it isn't built yet.

**Comment by natoscott** [comment] 2015-04-09 23:48
Is it possible this Ubuntu version is not using gzipped man pages?  (maybe uses xz, bz2 or some other compression, perhaps).  The PCP build infrastructure assumes, via debian/libpcp3-dev.install contents, that gzipped is being used since thats what all Debian distros have traditionally done.

That's a guess though - could be some other reason that .gz file is not being generated.  Might be worth looking into the configure.ac file and determining which style of compressed man page is being built on your system.

**Comment by kmcdonell** [comment] 2015-12-20 23:58
I cannot reproduce this.  On my QA machine
kenj@vm00:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="12.04.5 LTS, Precise Pangolin"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu precise (12.04.5 LTS)"
VERSION_ID="12.04"

where the build runs to completion (and has been doing so twice a week, forever), and after I install the packages ...

kenj@vm00:~$ dpkg -S /usr/share/man/man3/LOGIMPORT.3.gz
libpcp3-dev: /usr/share/man/man3/LOGIMPORT.3.gz

So, unless gwillem can provide us with some more information (the Logs/pcp file would be a helpful start), I'm inclined to close this.

**Comment by natoscott** [comment] 2016-01-08 03:27
Not reproduced on any of the several Ubuntu variants I have here either, so closing as per Kens comment.

**Closed by natoscott** 2016-01-08 03:27 UTC
Labels: bug, help wanted

**Comment by spiermar** [comment] 2016-04-27 23:45
@gwillem have you managed to solve this. having the same issue on Trusty (chroot)

**Comment by natoscott** [comment] 2016-04-28 00:10
@spiermar re your earlier mention of "(chroot)" - that might be the key - if you append ", manpages" to the Build-Depends line in debian/control does that fix it?

**Comment by spiermar** [comment] 2016-04-28 00:53
Tried installing manually and building from current master again, same problem. This is Jenkins slave and there's probably something different about it. Just not sure what yet.

**Comment by spiermar** [comment] 2016-04-28 00:58
Is "builld/deb/pcp-3.11.2/debian/pcp/usr/share/man/man3/LOGIMPORT.3.gz" the expected path? The file is there, just not UPPERCASE.

**Comment by natoscott** [comment] 2016-04-28 01:02
On the build slave, it'd be worth checking build/deb/pcp-3.x.y/src/include/builddefs file - it must end up with HAVE_GZIPPED_MANPAGES=true.

**Comment by spiermar** [comment] 2016-04-28 01:04
```
HAVE_GZIPPED_MANPAGES = true
HAVE_BZIP2ED_MANPAGES = false
HAVE_LZMAED_MANPAGES = false
```

**Comment by natoscott** [comment] 2016-04-28 01:05
Yes, that's expected - the INSTALL_MAN macro in builddefs ensures the appropriate case happens based on the contents/headers within each file.

**Comment by spiermar** [comment] 2016-04-28 01:07
But the cp command is trying "LOGIMPORT.3.gz", and that doesn't exist. Just the lowercase version, "logimport.3.gz".

**Comment by natoscott** [comment] 2016-04-28 01:17
Yeah, IIRC that INSTALL_MAN macro picks out the correct name to use (can be multiple, can be a mix of upper/lower case) from the ".sh NAME" section in the man page, and uses that.  For logimport.3 it's:

.SH NAME
\f3LOGIMPORT\f1 \- introduction to the library for importing data and creating a PCP archive

... that's where the upper casing comes from.  Somehow though we are ending up with the destination file missing from below build/deb/pcp-3.x.y/debian/libpcp3-dev/ though.

**Comment by natoscott** [comment] 2016-05-10 06:34
@spiermar Martin, I've still not reproduced this, but working on someone's machine who had, I think git pcp master may offer some relief on this issue.  Please let me know, either way?  Thanks!

**Comment by spiermar** [comment] 2016-05-10 16:19
I can try again. I managed to reproduce it consistently, but only on Jenkins. Directly on host, it builds just fine. I'll try it later today and let you know.

**Comment by spiermar** [comment] 2016-05-11 15:45
@natoscott apparently it helped. I managed to build PCP on our Jenkins nodes just fine now.

**Comment by natoscott** [comment] 2016-05-11 23:37
@spiermar great, thanks Martin.  I have another person also reporting a now-working build, so looks like this one is finally resolved.
